// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package core

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPlanChangeExecutor creates a new instance of MockPlanChangeExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlanChangeExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlanChangeExecutor {
	mock := &MockPlanChangeExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPlanChangeExecutor is an autogenerated mock type for the PlanChangeExecutor type
type MockPlanChangeExecutor struct {
	mock.Mock
}

type MockPlanChangeExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlanChangeExecutor) EXPECT() *MockPlanChangeExecutor_Expecter {
	return &MockPlanChangeExecutor_Expecter{mock: &_m.Mock}
}

// ExecutePlanChange provides a mock function for the type MockPlanChangeExecutor
func (_mock *MockPlanChangeExecutor) ExecutePlanChange(ctx context.Context, userID uint, newPeriodID uint) (*PlanChangeResult, error) {
	ret := _mock.Called(ctx, userID, newPeriodID)

	if len(ret) == 0 {
		panic("no return value specified for ExecutePlanChange")
	}

	var r0 *PlanChangeResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) (*PlanChangeResult, error)); ok {
		return returnFunc(ctx, userID, newPeriodID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) *PlanChangeResult); ok {
		r0 = returnFunc(ctx, userID, newPeriodID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*PlanChangeResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = returnFunc(ctx, userID, newPeriodID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlanChangeExecutor_ExecutePlanChange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecutePlanChange'
type MockPlanChangeExecutor_ExecutePlanChange_Call struct {
	*mock.Call
}

// ExecutePlanChange is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - newPeriodID uint
func (_e *MockPlanChangeExecutor_Expecter) ExecutePlanChange(ctx interface{}, userID interface{}, newPeriodID interface{}) *MockPlanChangeExecutor_ExecutePlanChange_Call {
	return &MockPlanChangeExecutor_ExecutePlanChange_Call{Call: _e.mock.On("ExecutePlanChange", ctx, userID, newPeriodID)}
}

func (_c *MockPlanChangeExecutor_ExecutePlanChange_Call) Run(run func(ctx context.Context, userID uint, newPeriodID uint)) *MockPlanChangeExecutor_ExecutePlanChange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPlanChangeExecutor_ExecutePlanChange_Call) Return(planChangeResult *PlanChangeResult, err error) *MockPlanChangeExecutor_ExecutePlanChange_Call {
	_c.Call.Return(planChangeResult, err)
	return _c
}

func (_c *MockPlanChangeExecutor_ExecutePlanChange_Call) RunAndReturn(run func(ctx context.Context, userID uint, newPeriodID uint) (*PlanChangeResult, error)) *MockPlanChangeExecutor_ExecutePlanChange_Call {
	_c.Call.Return(run)
	return _c
}
