// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package core

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCheckoutProvider creates a new instance of MockCheckoutProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCheckoutProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCheckoutProvider {
	mock := &MockCheckoutProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCheckoutProvider is an autogenerated mock type for the CheckoutProvider type
type MockCheckoutProvider struct {
	mock.Mock
}

type MockCheckoutProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCheckoutProvider) EXPECT() *MockCheckoutProvider_Expecter {
	return &MockCheckoutProvider_Expecter{mock: &_m.Mock}
}

// GetCheckoutUI provides a mock function for the type MockCheckoutProvider
func (_mock *MockCheckoutProvider) GetCheckoutUI(ctx context.Context, userID uint, planID uint, periodID uint) (*CheckoutUIResponse, error) {
	ret := _mock.Called(ctx, userID, planID, periodID)

	if len(ret) == 0 {
		panic("no return value specified for GetCheckoutUI")
	}

	var r0 *CheckoutUIResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, uint) (*CheckoutUIResponse, error)); ok {
		return returnFunc(ctx, userID, planID, periodID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, uint) *CheckoutUIResponse); ok {
		r0 = returnFunc(ctx, userID, planID, periodID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CheckoutUIResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, uint, uint) error); ok {
		r1 = returnFunc(ctx, userID, planID, periodID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCheckoutProvider_GetCheckoutUI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCheckoutUI'
type MockCheckoutProvider_GetCheckoutUI_Call struct {
	*mock.Call
}

// GetCheckoutUI is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - planID uint
//   - periodID uint
func (_e *MockCheckoutProvider_Expecter) GetCheckoutUI(ctx interface{}, userID interface{}, planID interface{}, periodID interface{}) *MockCheckoutProvider_GetCheckoutUI_Call {
	return &MockCheckoutProvider_GetCheckoutUI_Call{Call: _e.mock.On("GetCheckoutUI", ctx, userID, planID, periodID)}
}

func (_c *MockCheckoutProvider_GetCheckoutUI_Call) Run(run func(ctx context.Context, userID uint, planID uint, periodID uint)) *MockCheckoutProvider_GetCheckoutUI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		var arg3 uint
		if args[3] != nil {
			arg3 = args[3].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCheckoutProvider_GetCheckoutUI_Call) Return(checkoutUIResponse *CheckoutUIResponse, err error) *MockCheckoutProvider_GetCheckoutUI_Call {
	_c.Call.Return(checkoutUIResponse, err)
	return _c
}

func (_c *MockCheckoutProvider_GetCheckoutUI_Call) RunAndReturn(run func(ctx context.Context, userID uint, planID uint, periodID uint) (*CheckoutUIResponse, error)) *MockCheckoutProvider_GetCheckoutUI_Call {
	_c.Call.Return(run)
	return _c
}
