// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package core

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockGatewayIdentity creates a new instance of MockGatewayIdentity. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGatewayIdentity(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGatewayIdentity {
	mock := &MockGatewayIdentity{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGatewayIdentity is an autogenerated mock type for the GatewayIdentity type
type MockGatewayIdentity struct {
	mock.Mock
}

type MockGatewayIdentity_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGatewayIdentity) EXPECT() *MockGatewayIdentity_Expecter {
	return &MockGatewayIdentity_Expecter{mock: &_m.Mock}
}

// GetDescription provides a mock function for the type MockGatewayIdentity
func (_mock *MockGatewayIdentity) GetDescription(ctx context.Context) string {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDescription")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockGatewayIdentity_GetDescription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDescription'
type MockGatewayIdentity_GetDescription_Call struct {
	*mock.Call
}

// GetDescription is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGatewayIdentity_Expecter) GetDescription(ctx interface{}) *MockGatewayIdentity_GetDescription_Call {
	return &MockGatewayIdentity_GetDescription_Call{Call: _e.mock.On("GetDescription", ctx)}
}

func (_c *MockGatewayIdentity_GetDescription_Call) Run(run func(ctx context.Context)) *MockGatewayIdentity_GetDescription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGatewayIdentity_GetDescription_Call) Return(s string) *MockGatewayIdentity_GetDescription_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockGatewayIdentity_GetDescription_Call) RunAndReturn(run func(ctx context.Context) string) *MockGatewayIdentity_GetDescription_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogo provides a mock function for the type MockGatewayIdentity
func (_mock *MockGatewayIdentity) GetLogo(ctx context.Context) ([]byte, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLogo")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]byte, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []byte); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGatewayIdentity_GetLogo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogo'
type MockGatewayIdentity_GetLogo_Call struct {
	*mock.Call
}

// GetLogo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGatewayIdentity_Expecter) GetLogo(ctx interface{}) *MockGatewayIdentity_GetLogo_Call {
	return &MockGatewayIdentity_GetLogo_Call{Call: _e.mock.On("GetLogo", ctx)}
}

func (_c *MockGatewayIdentity_GetLogo_Call) Run(run func(ctx context.Context)) *MockGatewayIdentity_GetLogo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGatewayIdentity_GetLogo_Call) Return(bytes []byte, err error) *MockGatewayIdentity_GetLogo_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockGatewayIdentity_GetLogo_Call) RunAndReturn(run func(ctx context.Context) ([]byte, error)) *MockGatewayIdentity_GetLogo_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function for the type MockGatewayIdentity
func (_mock *MockGatewayIdentity) GetName(ctx context.Context) string {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockGatewayIdentity_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type MockGatewayIdentity_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGatewayIdentity_Expecter) GetName(ctx interface{}) *MockGatewayIdentity_GetName_Call {
	return &MockGatewayIdentity_GetName_Call{Call: _e.mock.On("GetName", ctx)}
}

func (_c *MockGatewayIdentity_GetName_Call) Run(run func(ctx context.Context)) *MockGatewayIdentity_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGatewayIdentity_GetName_Call) Return(s string) *MockGatewayIdentity_GetName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockGatewayIdentity_GetName_Call) RunAndReturn(run func(ctx context.Context) string) *MockGatewayIdentity_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockGatewayIdentity
func (_mock *MockGatewayIdentity) ID(ctx context.Context) string {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockGatewayIdentity_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockGatewayIdentity_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGatewayIdentity_Expecter) ID(ctx interface{}) *MockGatewayIdentity_ID_Call {
	return &MockGatewayIdentity_ID_Call{Call: _e.mock.On("ID", ctx)}
}

func (_c *MockGatewayIdentity_ID_Call) Run(run func(ctx context.Context)) *MockGatewayIdentity_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGatewayIdentity_ID_Call) Return(s string) *MockGatewayIdentity_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockGatewayIdentity_ID_Call) RunAndReturn(run func(ctx context.Context) string) *MockGatewayIdentity_ID_Call {
	_c.Call.Return(run)
	return _c
}
