// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package core

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-plugin-billing/internal/db/models"
	"go.lumeweb.com/portal/config"
	"go.lumeweb.com/portal/core"
	"go.lumeweb.com/queryutil"
	"gorm.io/gorm"
)

// NewMockPricingService creates a new instance of MockPricingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPricingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPricingService {
	mock := &MockPricingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPricingService is an autogenerated mock type for the PricingService type
type MockPricingService struct {
	mock.Mock
}

type MockPricingService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPricingService) EXPECT() *MockPricingService_Expecter {
	return &MockPricingService_Expecter{mock: &_m.Mock}
}

// AddPlanToPriceLine provides a mock function for the type MockPricingService
func (_mock *MockPricingService) AddPlanToPriceLine(ctx context.Context, priceLineID uint, planID uint, position int) error {
	ret := _mock.Called(ctx, priceLineID, planID, position)

	if len(ret) == 0 {
		panic("no return value specified for AddPlanToPriceLine")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, int) error); ok {
		r0 = returnFunc(ctx, priceLineID, planID, position)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPricingService_AddPlanToPriceLine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPlanToPriceLine'
type MockPricingService_AddPlanToPriceLine_Call struct {
	*mock.Call
}

// AddPlanToPriceLine is a helper method to define mock.On call
//   - ctx context.Context
//   - priceLineID uint
//   - planID uint
//   - position int
func (_e *MockPricingService_Expecter) AddPlanToPriceLine(ctx interface{}, priceLineID interface{}, planID interface{}, position interface{}) *MockPricingService_AddPlanToPriceLine_Call {
	return &MockPricingService_AddPlanToPriceLine_Call{Call: _e.mock.On("AddPlanToPriceLine", ctx, priceLineID, planID, position)}
}

func (_c *MockPricingService_AddPlanToPriceLine_Call) Run(run func(ctx context.Context, priceLineID uint, planID uint, position int)) *MockPricingService_AddPlanToPriceLine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPricingService_AddPlanToPriceLine_Call) Return(err error) *MockPricingService_AddPlanToPriceLine_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPricingService_AddPlanToPriceLine_Call) RunAndReturn(run func(ctx context.Context, priceLineID uint, planID uint, position int) error) *MockPricingService_AddPlanToPriceLine_Call {
	_c.Call.Return(run)
	return _c
}

// AssignPriceLineToUser provides a mock function for the type MockPricingService
func (_mock *MockPricingService) AssignPriceLineToUser(ctx context.Context, userID uint, priceLineID uint) error {
	ret := _mock.Called(ctx, userID, priceLineID)

	if len(ret) == 0 {
		panic("no return value specified for AssignPriceLineToUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = returnFunc(ctx, userID, priceLineID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPricingService_AssignPriceLineToUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignPriceLineToUser'
type MockPricingService_AssignPriceLineToUser_Call struct {
	*mock.Call
}

// AssignPriceLineToUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - priceLineID uint
func (_e *MockPricingService_Expecter) AssignPriceLineToUser(ctx interface{}, userID interface{}, priceLineID interface{}) *MockPricingService_AssignPriceLineToUser_Call {
	return &MockPricingService_AssignPriceLineToUser_Call{Call: _e.mock.On("AssignPriceLineToUser", ctx, userID, priceLineID)}
}

func (_c *MockPricingService_AssignPriceLineToUser_Call) Run(run func(ctx context.Context, userID uint, priceLineID uint)) *MockPricingService_AssignPriceLineToUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPricingService_AssignPriceLineToUser_Call) Return(err error) *MockPricingService_AssignPriceLineToUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPricingService_AssignPriceLineToUser_Call) RunAndReturn(run func(ctx context.Context, userID uint, priceLineID uint) error) *MockPricingService_AssignPriceLineToUser_Call {
	_c.Call.Return(run)
	return _c
}

// Config provides a mock function for the type MockPricingService
func (_mock *MockPricingService) Config() config.Manager {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 config.Manager
	if returnFunc, ok := ret.Get(0).(func() config.Manager); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.Manager)
		}
	}
	return r0
}

// MockPricingService_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockPricingService_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockPricingService_Expecter) Config() *MockPricingService_Config_Call {
	return &MockPricingService_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockPricingService_Config_Call) Run(run func()) *MockPricingService_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPricingService_Config_Call) Return(manager config.Manager) *MockPricingService_Config_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockPricingService_Config_Call) RunAndReturn(run func() config.Manager) *MockPricingService_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function for the type MockPricingService
func (_mock *MockPricingService) Context() core.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 core.Context
	if returnFunc, ok := ret.Get(0).(func() core.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Context)
		}
	}
	return r0
}

// MockPricingService_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockPricingService_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockPricingService_Expecter) Context() *MockPricingService_Context_Call {
	return &MockPricingService_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockPricingService_Context_Call) Run(run func()) *MockPricingService_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPricingService_Context_Call) Return(context1 core.Context) *MockPricingService_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockPricingService_Context_Call) RunAndReturn(run func() core.Context) *MockPricingService_Context_Call {
	_c.Call.Return(run)
	return _c
}

// CreateGatewayProductMapping provides a mock function for the type MockPricingService
func (_mock *MockPricingService) CreateGatewayProductMapping(ctx context.Context, mapping *models.GatewayProductMapping) error {
	ret := _mock.Called(ctx, mapping)

	if len(ret) == 0 {
		panic("no return value specified for CreateGatewayProductMapping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.GatewayProductMapping) error); ok {
		r0 = returnFunc(ctx, mapping)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPricingService_CreateGatewayProductMapping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGatewayProductMapping'
type MockPricingService_CreateGatewayProductMapping_Call struct {
	*mock.Call
}

// CreateGatewayProductMapping is a helper method to define mock.On call
//   - ctx context.Context
//   - mapping *models.GatewayProductMapping
func (_e *MockPricingService_Expecter) CreateGatewayProductMapping(ctx interface{}, mapping interface{}) *MockPricingService_CreateGatewayProductMapping_Call {
	return &MockPricingService_CreateGatewayProductMapping_Call{Call: _e.mock.On("CreateGatewayProductMapping", ctx, mapping)}
}

func (_c *MockPricingService_CreateGatewayProductMapping_Call) Run(run func(ctx context.Context, mapping *models.GatewayProductMapping)) *MockPricingService_CreateGatewayProductMapping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.GatewayProductMapping
		if args[1] != nil {
			arg1 = args[1].(*models.GatewayProductMapping)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPricingService_CreateGatewayProductMapping_Call) Return(err error) *MockPricingService_CreateGatewayProductMapping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPricingService_CreateGatewayProductMapping_Call) RunAndReturn(run func(ctx context.Context, mapping *models.GatewayProductMapping) error) *MockPricingService_CreateGatewayProductMapping_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePriceLine provides a mock function for the type MockPricingService
func (_mock *MockPricingService) CreatePriceLine(ctx context.Context, line *models.PriceLine) error {
	ret := _mock.Called(ctx, line)

	if len(ret) == 0 {
		panic("no return value specified for CreatePriceLine")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.PriceLine) error); ok {
		r0 = returnFunc(ctx, line)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPricingService_CreatePriceLine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePriceLine'
type MockPricingService_CreatePriceLine_Call struct {
	*mock.Call
}

// CreatePriceLine is a helper method to define mock.On call
//   - ctx context.Context
//   - line *models.PriceLine
func (_e *MockPricingService_Expecter) CreatePriceLine(ctx interface{}, line interface{}) *MockPricingService_CreatePriceLine_Call {
	return &MockPricingService_CreatePriceLine_Call{Call: _e.mock.On("CreatePriceLine", ctx, line)}
}

func (_c *MockPricingService_CreatePriceLine_Call) Run(run func(ctx context.Context, line *models.PriceLine)) *MockPricingService_CreatePriceLine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.PriceLine
		if args[1] != nil {
			arg1 = args[1].(*models.PriceLine)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPricingService_CreatePriceLine_Call) Return(err error) *MockPricingService_CreatePriceLine_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPricingService_CreatePriceLine_Call) RunAndReturn(run func(ctx context.Context, line *models.PriceLine) error) *MockPricingService_CreatePriceLine_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePricingPlan provides a mock function for the type MockPricingService
func (_mock *MockPricingService) CreatePricingPlan(ctx context.Context, plan *models.PricingPlan) error {
	ret := _mock.Called(ctx, plan)

	if len(ret) == 0 {
		panic("no return value specified for CreatePricingPlan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.PricingPlan) error); ok {
		r0 = returnFunc(ctx, plan)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPricingService_CreatePricingPlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePricingPlan'
type MockPricingService_CreatePricingPlan_Call struct {
	*mock.Call
}

// CreatePricingPlan is a helper method to define mock.On call
//   - ctx context.Context
//   - plan *models.PricingPlan
func (_e *MockPricingService_Expecter) CreatePricingPlan(ctx interface{}, plan interface{}) *MockPricingService_CreatePricingPlan_Call {
	return &MockPricingService_CreatePricingPlan_Call{Call: _e.mock.On("CreatePricingPlan", ctx, plan)}
}

func (_c *MockPricingService_CreatePricingPlan_Call) Run(run func(ctx context.Context, plan *models.PricingPlan)) *MockPricingService_CreatePricingPlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.PricingPlan
		if args[1] != nil {
			arg1 = args[1].(*models.PricingPlan)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPricingService_CreatePricingPlan_Call) Return(err error) *MockPricingService_CreatePricingPlan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPricingService_CreatePricingPlan_Call) RunAndReturn(run func(ctx context.Context, plan *models.PricingPlan) error) *MockPricingService_CreatePricingPlan_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePricingPlanPeriod provides a mock function for the type MockPricingService
func (_mock *MockPricingService) CreatePricingPlanPeriod(ctx context.Context, period *models.PricingPlanPeriod) error {
	ret := _mock.Called(ctx, period)

	if len(ret) == 0 {
		panic("no return value specified for CreatePricingPlanPeriod")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.PricingPlanPeriod) error); ok {
		r0 = returnFunc(ctx, period)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPricingService_CreatePricingPlanPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePricingPlanPeriod'
type MockPricingService_CreatePricingPlanPeriod_Call struct {
	*mock.Call
}

// CreatePricingPlanPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - period *models.PricingPlanPeriod
func (_e *MockPricingService_Expecter) CreatePricingPlanPeriod(ctx interface{}, period interface{}) *MockPricingService_CreatePricingPlanPeriod_Call {
	return &MockPricingService_CreatePricingPlanPeriod_Call{Call: _e.mock.On("CreatePricingPlanPeriod", ctx, period)}
}

func (_c *MockPricingService_CreatePricingPlanPeriod_Call) Run(run func(ctx context.Context, period *models.PricingPlanPeriod)) *MockPricingService_CreatePricingPlanPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.PricingPlanPeriod
		if args[1] != nil {
			arg1 = args[1].(*models.PricingPlanPeriod)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPricingService_CreatePricingPlanPeriod_Call) Return(err error) *MockPricingService_CreatePricingPlanPeriod_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPricingService_CreatePricingPlanPeriod_Call) RunAndReturn(run func(ctx context.Context, period *models.PricingPlanPeriod) error) *MockPricingService_CreatePricingPlanPeriod_Call {
	_c.Call.Return(run)
	return _c
}

// DB provides a mock function for the type MockPricingService
func (_mock *MockPricingService) DB() *gorm.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DB")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockPricingService_DB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DB'
type MockPricingService_DB_Call struct {
	*mock.Call
}

// DB is a helper method to define mock.On call
func (_e *MockPricingService_Expecter) DB() *MockPricingService_DB_Call {
	return &MockPricingService_DB_Call{Call: _e.mock.On("DB")}
}

func (_c *MockPricingService_DB_Call) Run(run func()) *MockPricingService_DB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPricingService_DB_Call) Return(dB *gorm.DB) *MockPricingService_DB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockPricingService_DB_Call) RunAndReturn(run func() *gorm.DB) *MockPricingService_DB_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteGatewayProductMapping provides a mock function for the type MockPricingService
func (_mock *MockPricingService) DeleteGatewayProductMapping(ctx context.Context, id uint) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteGatewayProductMapping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPricingService_DeleteGatewayProductMapping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteGatewayProductMapping'
type MockPricingService_DeleteGatewayProductMapping_Call struct {
	*mock.Call
}

// DeleteGatewayProductMapping is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockPricingService_Expecter) DeleteGatewayProductMapping(ctx interface{}, id interface{}) *MockPricingService_DeleteGatewayProductMapping_Call {
	return &MockPricingService_DeleteGatewayProductMapping_Call{Call: _e.mock.On("DeleteGatewayProductMapping", ctx, id)}
}

func (_c *MockPricingService_DeleteGatewayProductMapping_Call) Run(run func(ctx context.Context, id uint)) *MockPricingService_DeleteGatewayProductMapping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPricingService_DeleteGatewayProductMapping_Call) Return(err error) *MockPricingService_DeleteGatewayProductMapping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPricingService_DeleteGatewayProductMapping_Call) RunAndReturn(run func(ctx context.Context, id uint) error) *MockPricingService_DeleteGatewayProductMapping_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePriceLine provides a mock function for the type MockPricingService
func (_mock *MockPricingService) DeletePriceLine(ctx context.Context, id uint) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeletePriceLine")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPricingService_DeletePriceLine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePriceLine'
type MockPricingService_DeletePriceLine_Call struct {
	*mock.Call
}

// DeletePriceLine is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockPricingService_Expecter) DeletePriceLine(ctx interface{}, id interface{}) *MockPricingService_DeletePriceLine_Call {
	return &MockPricingService_DeletePriceLine_Call{Call: _e.mock.On("DeletePriceLine", ctx, id)}
}

func (_c *MockPricingService_DeletePriceLine_Call) Run(run func(ctx context.Context, id uint)) *MockPricingService_DeletePriceLine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPricingService_DeletePriceLine_Call) Return(err error) *MockPricingService_DeletePriceLine_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPricingService_DeletePriceLine_Call) RunAndReturn(run func(ctx context.Context, id uint) error) *MockPricingService_DeletePriceLine_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePricingPlan provides a mock function for the type MockPricingService
func (_mock *MockPricingService) DeletePricingPlan(ctx context.Context, id uint) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeletePricingPlan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPricingService_DeletePricingPlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePricingPlan'
type MockPricingService_DeletePricingPlan_Call struct {
	*mock.Call
}

// DeletePricingPlan is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockPricingService_Expecter) DeletePricingPlan(ctx interface{}, id interface{}) *MockPricingService_DeletePricingPlan_Call {
	return &MockPricingService_DeletePricingPlan_Call{Call: _e.mock.On("DeletePricingPlan", ctx, id)}
}

func (_c *MockPricingService_DeletePricingPlan_Call) Run(run func(ctx context.Context, id uint)) *MockPricingService_DeletePricingPlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPricingService_DeletePricingPlan_Call) Return(err error) *MockPricingService_DeletePricingPlan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPricingService_DeletePricingPlan_Call) RunAndReturn(run func(ctx context.Context, id uint) error) *MockPricingService_DeletePricingPlan_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePricingPlanPeriod provides a mock function for the type MockPricingService
func (_mock *MockPricingService) DeletePricingPlanPeriod(ctx context.Context, id uint) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeletePricingPlanPeriod")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPricingService_DeletePricingPlanPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePricingPlanPeriod'
type MockPricingService_DeletePricingPlanPeriod_Call struct {
	*mock.Call
}

// DeletePricingPlanPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockPricingService_Expecter) DeletePricingPlanPeriod(ctx interface{}, id interface{}) *MockPricingService_DeletePricingPlanPeriod_Call {
	return &MockPricingService_DeletePricingPlanPeriod_Call{Call: _e.mock.On("DeletePricingPlanPeriod", ctx, id)}
}

func (_c *MockPricingService_DeletePricingPlanPeriod_Call) Run(run func(ctx context.Context, id uint)) *MockPricingService_DeletePricingPlanPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPricingService_DeletePricingPlanPeriod_Call) Return(err error) *MockPricingService_DeletePricingPlanPeriod_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPricingService_DeletePricingPlanPeriod_Call) RunAndReturn(run func(ctx context.Context, id uint) error) *MockPricingService_DeletePricingPlanPeriod_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfig provides a mock function for the type MockPricingService
func (_mock *MockPricingService) GetConfig() (any, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (any, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPricingService_GetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfig'
type MockPricingService_GetConfig_Call struct {
	*mock.Call
}

// GetConfig is a helper method to define mock.On call
func (_e *MockPricingService_Expecter) GetConfig() *MockPricingService_GetConfig_Call {
	return &MockPricingService_GetConfig_Call{Call: _e.mock.On("GetConfig")}
}

func (_c *MockPricingService_GetConfig_Call) Run(run func()) *MockPricingService_GetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPricingService_GetConfig_Call) Return(v any, err error) *MockPricingService_GetConfig_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockPricingService_GetConfig_Call) RunAndReturn(run func() (any, error)) *MockPricingService_GetConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetDefaultPriceLine provides a mock function for the type MockPricingService
func (_mock *MockPricingService) GetDefaultPriceLine(ctx context.Context) (*models.PriceLine, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDefaultPriceLine")
	}

	var r0 *models.PriceLine
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*models.PriceLine, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *models.PriceLine); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PriceLine)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPricingService_GetDefaultPriceLine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDefaultPriceLine'
type MockPricingService_GetDefaultPriceLine_Call struct {
	*mock.Call
}

// GetDefaultPriceLine is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPricingService_Expecter) GetDefaultPriceLine(ctx interface{}) *MockPricingService_GetDefaultPriceLine_Call {
	return &MockPricingService_GetDefaultPriceLine_Call{Call: _e.mock.On("GetDefaultPriceLine", ctx)}
}

func (_c *MockPricingService_GetDefaultPriceLine_Call) Run(run func(ctx context.Context)) *MockPricingService_GetDefaultPriceLine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPricingService_GetDefaultPriceLine_Call) Return(priceLine *models.PriceLine, err error) *MockPricingService_GetDefaultPriceLine_Call {
	_c.Call.Return(priceLine, err)
	return _c
}

func (_c *MockPricingService_GetDefaultPriceLine_Call) RunAndReturn(run func(ctx context.Context) (*models.PriceLine, error)) *MockPricingService_GetDefaultPriceLine_Call {
	_c.Call.Return(run)
	return _c
}

// GetEffectivePriceLineForUser provides a mock function for the type MockPricingService
func (_mock *MockPricingService) GetEffectivePriceLineForUser(ctx context.Context, userID uint) (*models.PriceLine, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetEffectivePriceLineForUser")
	}

	var r0 *models.PriceLine
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*models.PriceLine, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *models.PriceLine); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PriceLine)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPricingService_GetEffectivePriceLineForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEffectivePriceLineForUser'
type MockPricingService_GetEffectivePriceLineForUser_Call struct {
	*mock.Call
}

// GetEffectivePriceLineForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockPricingService_Expecter) GetEffectivePriceLineForUser(ctx interface{}, userID interface{}) *MockPricingService_GetEffectivePriceLineForUser_Call {
	return &MockPricingService_GetEffectivePriceLineForUser_Call{Call: _e.mock.On("GetEffectivePriceLineForUser", ctx, userID)}
}

func (_c *MockPricingService_GetEffectivePriceLineForUser_Call) Run(run func(ctx context.Context, userID uint)) *MockPricingService_GetEffectivePriceLineForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPricingService_GetEffectivePriceLineForUser_Call) Return(priceLine *models.PriceLine, err error) *MockPricingService_GetEffectivePriceLineForUser_Call {
	_c.Call.Return(priceLine, err)
	return _c
}

func (_c *MockPricingService_GetEffectivePriceLineForUser_Call) RunAndReturn(run func(ctx context.Context, userID uint) (*models.PriceLine, error)) *MockPricingService_GetEffectivePriceLineForUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetGatewayProductMapping provides a mock function for the type MockPricingService
func (_mock *MockPricingService) GetGatewayProductMapping(ctx context.Context, planID uint, gatewayType string) (*models.GatewayProductMapping, error) {
	ret := _mock.Called(ctx, planID, gatewayType)

	if len(ret) == 0 {
		panic("no return value specified for GetGatewayProductMapping")
	}

	var r0 *models.GatewayProductMapping
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string) (*models.GatewayProductMapping, error)); ok {
		return returnFunc(ctx, planID, gatewayType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string) *models.GatewayProductMapping); ok {
		r0 = returnFunc(ctx, planID, gatewayType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.GatewayProductMapping)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, string) error); ok {
		r1 = returnFunc(ctx, planID, gatewayType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPricingService_GetGatewayProductMapping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGatewayProductMapping'
type MockPricingService_GetGatewayProductMapping_Call struct {
	*mock.Call
}

// GetGatewayProductMapping is a helper method to define mock.On call
//   - ctx context.Context
//   - planID uint
//   - gatewayType string
func (_e *MockPricingService_Expecter) GetGatewayProductMapping(ctx interface{}, planID interface{}, gatewayType interface{}) *MockPricingService_GetGatewayProductMapping_Call {
	return &MockPricingService_GetGatewayProductMapping_Call{Call: _e.mock.On("GetGatewayProductMapping", ctx, planID, gatewayType)}
}

func (_c *MockPricingService_GetGatewayProductMapping_Call) Run(run func(ctx context.Context, planID uint, gatewayType string)) *MockPricingService_GetGatewayProductMapping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPricingService_GetGatewayProductMapping_Call) Return(gatewayProductMapping *models.GatewayProductMapping, err error) *MockPricingService_GetGatewayProductMapping_Call {
	_c.Call.Return(gatewayProductMapping, err)
	return _c
}

func (_c *MockPricingService_GetGatewayProductMapping_Call) RunAndReturn(run func(ctx context.Context, planID uint, gatewayType string) (*models.GatewayProductMapping, error)) *MockPricingService_GetGatewayProductMapping_Call {
	_c.Call.Return(run)
	return _c
}

// GetGatewayProductMappingsByPlan provides a mock function for the type MockPricingService
func (_mock *MockPricingService) GetGatewayProductMappingsByPlan(ctx context.Context, planID uint) ([]*models.GatewayProductMapping, error) {
	ret := _mock.Called(ctx, planID)

	if len(ret) == 0 {
		panic("no return value specified for GetGatewayProductMappingsByPlan")
	}

	var r0 []*models.GatewayProductMapping
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) ([]*models.GatewayProductMapping, error)); ok {
		return returnFunc(ctx, planID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) []*models.GatewayProductMapping); ok {
		r0 = returnFunc(ctx, planID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.GatewayProductMapping)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, planID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPricingService_GetGatewayProductMappingsByPlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGatewayProductMappingsByPlan'
type MockPricingService_GetGatewayProductMappingsByPlan_Call struct {
	*mock.Call
}

// GetGatewayProductMappingsByPlan is a helper method to define mock.On call
//   - ctx context.Context
//   - planID uint
func (_e *MockPricingService_Expecter) GetGatewayProductMappingsByPlan(ctx interface{}, planID interface{}) *MockPricingService_GetGatewayProductMappingsByPlan_Call {
	return &MockPricingService_GetGatewayProductMappingsByPlan_Call{Call: _e.mock.On("GetGatewayProductMappingsByPlan", ctx, planID)}
}

func (_c *MockPricingService_GetGatewayProductMappingsByPlan_Call) Run(run func(ctx context.Context, planID uint)) *MockPricingService_GetGatewayProductMappingsByPlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPricingService_GetGatewayProductMappingsByPlan_Call) Return(gatewayProductMappings []*models.GatewayProductMapping, err error) *MockPricingService_GetGatewayProductMappingsByPlan_Call {
	_c.Call.Return(gatewayProductMappings, err)
	return _c
}

func (_c *MockPricingService_GetGatewayProductMappingsByPlan_Call) RunAndReturn(run func(ctx context.Context, planID uint) ([]*models.GatewayProductMapping, error)) *MockPricingService_GetGatewayProductMappingsByPlan_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingSyncMappings provides a mock function for the type MockPricingService
func (_mock *MockPricingService) GetPendingSyncMappings(ctx context.Context, gatewayType string) ([]*models.GatewayProductMapping, error) {
	ret := _mock.Called(ctx, gatewayType)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingSyncMappings")
	}

	var r0 []*models.GatewayProductMapping
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*models.GatewayProductMapping, error)); ok {
		return returnFunc(ctx, gatewayType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*models.GatewayProductMapping); ok {
		r0 = returnFunc(ctx, gatewayType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.GatewayProductMapping)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, gatewayType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPricingService_GetPendingSyncMappings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingSyncMappings'
type MockPricingService_GetPendingSyncMappings_Call struct {
	*mock.Call
}

// GetPendingSyncMappings is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayType string
func (_e *MockPricingService_Expecter) GetPendingSyncMappings(ctx interface{}, gatewayType interface{}) *MockPricingService_GetPendingSyncMappings_Call {
	return &MockPricingService_GetPendingSyncMappings_Call{Call: _e.mock.On("GetPendingSyncMappings", ctx, gatewayType)}
}

func (_c *MockPricingService_GetPendingSyncMappings_Call) Run(run func(ctx context.Context, gatewayType string)) *MockPricingService_GetPendingSyncMappings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPricingService_GetPendingSyncMappings_Call) Return(gatewayProductMappings []*models.GatewayProductMapping, err error) *MockPricingService_GetPendingSyncMappings_Call {
	_c.Call.Return(gatewayProductMappings, err)
	return _c
}

func (_c *MockPricingService_GetPendingSyncMappings_Call) RunAndReturn(run func(ctx context.Context, gatewayType string) ([]*models.GatewayProductMapping, error)) *MockPricingService_GetPendingSyncMappings_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlansForPriceLine provides a mock function for the type MockPricingService
func (_mock *MockPricingService) GetPlansForPriceLine(ctx context.Context, priceLineID uint) ([]*models.PricingPlan, error) {
	ret := _mock.Called(ctx, priceLineID)

	if len(ret) == 0 {
		panic("no return value specified for GetPlansForPriceLine")
	}

	var r0 []*models.PricingPlan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) ([]*models.PricingPlan, error)); ok {
		return returnFunc(ctx, priceLineID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) []*models.PricingPlan); ok {
		r0 = returnFunc(ctx, priceLineID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PricingPlan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, priceLineID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPricingService_GetPlansForPriceLine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlansForPriceLine'
type MockPricingService_GetPlansForPriceLine_Call struct {
	*mock.Call
}

// GetPlansForPriceLine is a helper method to define mock.On call
//   - ctx context.Context
//   - priceLineID uint
func (_e *MockPricingService_Expecter) GetPlansForPriceLine(ctx interface{}, priceLineID interface{}) *MockPricingService_GetPlansForPriceLine_Call {
	return &MockPricingService_GetPlansForPriceLine_Call{Call: _e.mock.On("GetPlansForPriceLine", ctx, priceLineID)}
}

func (_c *MockPricingService_GetPlansForPriceLine_Call) Run(run func(ctx context.Context, priceLineID uint)) *MockPricingService_GetPlansForPriceLine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPricingService_GetPlansForPriceLine_Call) Return(pricingPlans []*models.PricingPlan, err error) *MockPricingService_GetPlansForPriceLine_Call {
	_c.Call.Return(pricingPlans, err)
	return _c
}

func (_c *MockPricingService_GetPlansForPriceLine_Call) RunAndReturn(run func(ctx context.Context, priceLineID uint) ([]*models.PricingPlan, error)) *MockPricingService_GetPlansForPriceLine_Call {
	_c.Call.Return(run)
	return _c
}

// GetPriceLine provides a mock function for the type MockPricingService
func (_mock *MockPricingService) GetPriceLine(ctx context.Context, id uint) (*models.PriceLine, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPriceLine")
	}

	var r0 *models.PriceLine
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*models.PriceLine, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *models.PriceLine); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PriceLine)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPricingService_GetPriceLine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPriceLine'
type MockPricingService_GetPriceLine_Call struct {
	*mock.Call
}

// GetPriceLine is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockPricingService_Expecter) GetPriceLine(ctx interface{}, id interface{}) *MockPricingService_GetPriceLine_Call {
	return &MockPricingService_GetPriceLine_Call{Call: _e.mock.On("GetPriceLine", ctx, id)}
}

func (_c *MockPricingService_GetPriceLine_Call) Run(run func(ctx context.Context, id uint)) *MockPricingService_GetPriceLine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPricingService_GetPriceLine_Call) Return(priceLine *models.PriceLine, err error) *MockPricingService_GetPriceLine_Call {
	_c.Call.Return(priceLine, err)
	return _c
}

func (_c *MockPricingService_GetPriceLine_Call) RunAndReturn(run func(ctx context.Context, id uint) (*models.PriceLine, error)) *MockPricingService_GetPriceLine_Call {
	_c.Call.Return(run)
	return _c
}

// GetPriceLinePlans provides a mock function for the type MockPricingService
func (_mock *MockPricingService) GetPriceLinePlans(ctx context.Context, priceLineID uint) ([]*models.PriceLinePlan, error) {
	ret := _mock.Called(ctx, priceLineID)

	if len(ret) == 0 {
		panic("no return value specified for GetPriceLinePlans")
	}

	var r0 []*models.PriceLinePlan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) ([]*models.PriceLinePlan, error)); ok {
		return returnFunc(ctx, priceLineID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) []*models.PriceLinePlan); ok {
		r0 = returnFunc(ctx, priceLineID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PriceLinePlan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, priceLineID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPricingService_GetPriceLinePlans_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPriceLinePlans'
type MockPricingService_GetPriceLinePlans_Call struct {
	*mock.Call
}

// GetPriceLinePlans is a helper method to define mock.On call
//   - ctx context.Context
//   - priceLineID uint
func (_e *MockPricingService_Expecter) GetPriceLinePlans(ctx interface{}, priceLineID interface{}) *MockPricingService_GetPriceLinePlans_Call {
	return &MockPricingService_GetPriceLinePlans_Call{Call: _e.mock.On("GetPriceLinePlans", ctx, priceLineID)}
}

func (_c *MockPricingService_GetPriceLinePlans_Call) Run(run func(ctx context.Context, priceLineID uint)) *MockPricingService_GetPriceLinePlans_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPricingService_GetPriceLinePlans_Call) Return(priceLinePlans []*models.PriceLinePlan, err error) *MockPricingService_GetPriceLinePlans_Call {
	_c.Call.Return(priceLinePlans, err)
	return _c
}

func (_c *MockPricingService_GetPriceLinePlans_Call) RunAndReturn(run func(ctx context.Context, priceLineID uint) ([]*models.PriceLinePlan, error)) *MockPricingService_GetPriceLinePlans_Call {
	_c.Call.Return(run)
	return _c
}

// GetPriceLines provides a mock function for the type MockPricingService
func (_mock *MockPricingService) GetPriceLines(ctx context.Context, userID uint, filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]*models.PriceLine, int64, error) {
	ret := _mock.Called(ctx, userID, filters, sorts, pagination)

	if len(ret) == 0 {
		panic("no return value specified for GetPriceLines")
	}

	var r0 []*models.PriceLine
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) ([]*models.PriceLine, int64, error)); ok {
		return returnFunc(ctx, userID, filters, sorts, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) []*models.PriceLine); ok {
		r0 = returnFunc(ctx, userID, filters, sorts, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PriceLine)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) int64); ok {
		r1 = returnFunc(ctx, userID, filters, sorts, pagination)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uint, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) error); ok {
		r2 = returnFunc(ctx, userID, filters, sorts, pagination)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockPricingService_GetPriceLines_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPriceLines'
type MockPricingService_GetPriceLines_Call struct {
	*mock.Call
}

// GetPriceLines is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - filters []queryutil.CrudFilter
//   - sorts []queryutil.Sort
//   - pagination queryutil.Pagination
func (_e *MockPricingService_Expecter) GetPriceLines(ctx interface{}, userID interface{}, filters interface{}, sorts interface{}, pagination interface{}) *MockPricingService_GetPriceLines_Call {
	return &MockPricingService_GetPriceLines_Call{Call: _e.mock.On("GetPriceLines", ctx, userID, filters, sorts, pagination)}
}

func (_c *MockPricingService_GetPriceLines_Call) Run(run func(ctx context.Context, userID uint, filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination)) *MockPricingService_GetPriceLines_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 []queryutil.CrudFilter
		if args[2] != nil {
			arg2 = args[2].([]queryutil.CrudFilter)
		}
		var arg3 []queryutil.Sort
		if args[3] != nil {
			arg3 = args[3].([]queryutil.Sort)
		}
		var arg4 queryutil.Pagination
		if args[4] != nil {
			arg4 = args[4].(queryutil.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockPricingService_GetPriceLines_Call) Return(priceLines []*models.PriceLine, n int64, err error) *MockPricingService_GetPriceLines_Call {
	_c.Call.Return(priceLines, n, err)
	return _c
}

func (_c *MockPricingService_GetPriceLines_Call) RunAndReturn(run func(ctx context.Context, userID uint, filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]*models.PriceLine, int64, error)) *MockPricingService_GetPriceLines_Call {
	_c.Call.Return(run)
	return _c
}

// GetPriceLinesForPlan provides a mock function for the type MockPricingService
func (_mock *MockPricingService) GetPriceLinesForPlan(ctx context.Context, planID uint) ([]*models.PriceLinePlan, error) {
	ret := _mock.Called(ctx, planID)

	if len(ret) == 0 {
		panic("no return value specified for GetPriceLinesForPlan")
	}

	var r0 []*models.PriceLinePlan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) ([]*models.PriceLinePlan, error)); ok {
		return returnFunc(ctx, planID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) []*models.PriceLinePlan); ok {
		r0 = returnFunc(ctx, planID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PriceLinePlan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, planID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPricingService_GetPriceLinesForPlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPriceLinesForPlan'
type MockPricingService_GetPriceLinesForPlan_Call struct {
	*mock.Call
}

// GetPriceLinesForPlan is a helper method to define mock.On call
//   - ctx context.Context
//   - planID uint
func (_e *MockPricingService_Expecter) GetPriceLinesForPlan(ctx interface{}, planID interface{}) *MockPricingService_GetPriceLinesForPlan_Call {
	return &MockPricingService_GetPriceLinesForPlan_Call{Call: _e.mock.On("GetPriceLinesForPlan", ctx, planID)}
}

func (_c *MockPricingService_GetPriceLinesForPlan_Call) Run(run func(ctx context.Context, planID uint)) *MockPricingService_GetPriceLinesForPlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPricingService_GetPriceLinesForPlan_Call) Return(priceLinePlans []*models.PriceLinePlan, err error) *MockPricingService_GetPriceLinesForPlan_Call {
	_c.Call.Return(priceLinePlans, err)
	return _c
}

func (_c *MockPricingService_GetPriceLinesForPlan_Call) RunAndReturn(run func(ctx context.Context, planID uint) ([]*models.PriceLinePlan, error)) *MockPricingService_GetPriceLinesForPlan_Call {
	_c.Call.Return(run)
	return _c
}

// GetPricingPlan provides a mock function for the type MockPricingService
func (_mock *MockPricingService) GetPricingPlan(ctx context.Context, id uint) (*models.PricingPlan, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPricingPlan")
	}

	var r0 *models.PricingPlan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*models.PricingPlan, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *models.PricingPlan); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PricingPlan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPricingService_GetPricingPlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPricingPlan'
type MockPricingService_GetPricingPlan_Call struct {
	*mock.Call
}

// GetPricingPlan is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockPricingService_Expecter) GetPricingPlan(ctx interface{}, id interface{}) *MockPricingService_GetPricingPlan_Call {
	return &MockPricingService_GetPricingPlan_Call{Call: _e.mock.On("GetPricingPlan", ctx, id)}
}

func (_c *MockPricingService_GetPricingPlan_Call) Run(run func(ctx context.Context, id uint)) *MockPricingService_GetPricingPlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPricingService_GetPricingPlan_Call) Return(pricingPlan *models.PricingPlan, err error) *MockPricingService_GetPricingPlan_Call {
	_c.Call.Return(pricingPlan, err)
	return _c
}

func (_c *MockPricingService_GetPricingPlan_Call) RunAndReturn(run func(ctx context.Context, id uint) (*models.PricingPlan, error)) *MockPricingService_GetPricingPlan_Call {
	_c.Call.Return(run)
	return _c
}

// GetPricingPlanPeriod provides a mock function for the type MockPricingService
func (_mock *MockPricingService) GetPricingPlanPeriod(ctx context.Context, id uint) (*models.PricingPlanPeriod, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPricingPlanPeriod")
	}

	var r0 *models.PricingPlanPeriod
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*models.PricingPlanPeriod, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *models.PricingPlanPeriod); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PricingPlanPeriod)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPricingService_GetPricingPlanPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPricingPlanPeriod'
type MockPricingService_GetPricingPlanPeriod_Call struct {
	*mock.Call
}

// GetPricingPlanPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockPricingService_Expecter) GetPricingPlanPeriod(ctx interface{}, id interface{}) *MockPricingService_GetPricingPlanPeriod_Call {
	return &MockPricingService_GetPricingPlanPeriod_Call{Call: _e.mock.On("GetPricingPlanPeriod", ctx, id)}
}

func (_c *MockPricingService_GetPricingPlanPeriod_Call) Run(run func(ctx context.Context, id uint)) *MockPricingService_GetPricingPlanPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPricingService_GetPricingPlanPeriod_Call) Return(pricingPlanPeriod *models.PricingPlanPeriod, err error) *MockPricingService_GetPricingPlanPeriod_Call {
	_c.Call.Return(pricingPlanPeriod, err)
	return _c
}

func (_c *MockPricingService_GetPricingPlanPeriod_Call) RunAndReturn(run func(ctx context.Context, id uint) (*models.PricingPlanPeriod, error)) *MockPricingService_GetPricingPlanPeriod_Call {
	_c.Call.Return(run)
	return _c
}

// GetPricingPlanPeriods provides a mock function for the type MockPricingService
func (_mock *MockPricingService) GetPricingPlanPeriods(ctx context.Context, planID uint) ([]*models.PricingPlanPeriod, error) {
	ret := _mock.Called(ctx, planID)

	if len(ret) == 0 {
		panic("no return value specified for GetPricingPlanPeriods")
	}

	var r0 []*models.PricingPlanPeriod
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) ([]*models.PricingPlanPeriod, error)); ok {
		return returnFunc(ctx, planID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) []*models.PricingPlanPeriod); ok {
		r0 = returnFunc(ctx, planID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PricingPlanPeriod)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, planID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPricingService_GetPricingPlanPeriods_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPricingPlanPeriods'
type MockPricingService_GetPricingPlanPeriods_Call struct {
	*mock.Call
}

// GetPricingPlanPeriods is a helper method to define mock.On call
//   - ctx context.Context
//   - planID uint
func (_e *MockPricingService_Expecter) GetPricingPlanPeriods(ctx interface{}, planID interface{}) *MockPricingService_GetPricingPlanPeriods_Call {
	return &MockPricingService_GetPricingPlanPeriods_Call{Call: _e.mock.On("GetPricingPlanPeriods", ctx, planID)}
}

func (_c *MockPricingService_GetPricingPlanPeriods_Call) Run(run func(ctx context.Context, planID uint)) *MockPricingService_GetPricingPlanPeriods_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPricingService_GetPricingPlanPeriods_Call) Return(pricingPlanPeriods []*models.PricingPlanPeriod, err error) *MockPricingService_GetPricingPlanPeriods_Call {
	_c.Call.Return(pricingPlanPeriods, err)
	return _c
}

func (_c *MockPricingService_GetPricingPlanPeriods_Call) RunAndReturn(run func(ctx context.Context, planID uint) ([]*models.PricingPlanPeriod, error)) *MockPricingService_GetPricingPlanPeriods_Call {
	_c.Call.Return(run)
	return _c
}

// GetPricingPlanPeriodsWithFilter provides a mock function for the type MockPricingService
func (_mock *MockPricingService) GetPricingPlanPeriodsWithFilter(ctx context.Context, filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]*models.PricingPlanPeriod, int64, error) {
	ret := _mock.Called(ctx, filters, sorts, pagination)

	if len(ret) == 0 {
		panic("no return value specified for GetPricingPlanPeriodsWithFilter")
	}

	var r0 []*models.PricingPlanPeriod
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) ([]*models.PricingPlanPeriod, int64, error)); ok {
		return returnFunc(ctx, filters, sorts, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) []*models.PricingPlanPeriod); ok {
		r0 = returnFunc(ctx, filters, sorts, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PricingPlanPeriod)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) int64); ok {
		r1 = returnFunc(ctx, filters, sorts, pagination)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) error); ok {
		r2 = returnFunc(ctx, filters, sorts, pagination)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockPricingService_GetPricingPlanPeriodsWithFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPricingPlanPeriodsWithFilter'
type MockPricingService_GetPricingPlanPeriodsWithFilter_Call struct {
	*mock.Call
}

// GetPricingPlanPeriodsWithFilter is a helper method to define mock.On call
//   - ctx context.Context
//   - filters []queryutil.CrudFilter
//   - sorts []queryutil.Sort
//   - pagination queryutil.Pagination
func (_e *MockPricingService_Expecter) GetPricingPlanPeriodsWithFilter(ctx interface{}, filters interface{}, sorts interface{}, pagination interface{}) *MockPricingService_GetPricingPlanPeriodsWithFilter_Call {
	return &MockPricingService_GetPricingPlanPeriodsWithFilter_Call{Call: _e.mock.On("GetPricingPlanPeriodsWithFilter", ctx, filters, sorts, pagination)}
}

func (_c *MockPricingService_GetPricingPlanPeriodsWithFilter_Call) Run(run func(ctx context.Context, filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination)) *MockPricingService_GetPricingPlanPeriodsWithFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []queryutil.CrudFilter
		if args[1] != nil {
			arg1 = args[1].([]queryutil.CrudFilter)
		}
		var arg2 []queryutil.Sort
		if args[2] != nil {
			arg2 = args[2].([]queryutil.Sort)
		}
		var arg3 queryutil.Pagination
		if args[3] != nil {
			arg3 = args[3].(queryutil.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPricingService_GetPricingPlanPeriodsWithFilter_Call) Return(pricingPlanPeriods []*models.PricingPlanPeriod, n int64, err error) *MockPricingService_GetPricingPlanPeriodsWithFilter_Call {
	_c.Call.Return(pricingPlanPeriods, n, err)
	return _c
}

func (_c *MockPricingService_GetPricingPlanPeriodsWithFilter_Call) RunAndReturn(run func(ctx context.Context, filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]*models.PricingPlanPeriod, int64, error)) *MockPricingService_GetPricingPlanPeriodsWithFilter_Call {
	_c.Call.Return(run)
	return _c
}

// GetPricingPlans provides a mock function for the type MockPricingService
func (_mock *MockPricingService) GetPricingPlans(ctx context.Context, userID uint, filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]*models.PricingPlan, int64, error) {
	ret := _mock.Called(ctx, userID, filters, sorts, pagination)

	if len(ret) == 0 {
		panic("no return value specified for GetPricingPlans")
	}

	var r0 []*models.PricingPlan
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) ([]*models.PricingPlan, int64, error)); ok {
		return returnFunc(ctx, userID, filters, sorts, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) []*models.PricingPlan); ok {
		r0 = returnFunc(ctx, userID, filters, sorts, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PricingPlan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) int64); ok {
		r1 = returnFunc(ctx, userID, filters, sorts, pagination)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uint, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) error); ok {
		r2 = returnFunc(ctx, userID, filters, sorts, pagination)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockPricingService_GetPricingPlans_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPricingPlans'
type MockPricingService_GetPricingPlans_Call struct {
	*mock.Call
}

// GetPricingPlans is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - filters []queryutil.CrudFilter
//   - sorts []queryutil.Sort
//   - pagination queryutil.Pagination
func (_e *MockPricingService_Expecter) GetPricingPlans(ctx interface{}, userID interface{}, filters interface{}, sorts interface{}, pagination interface{}) *MockPricingService_GetPricingPlans_Call {
	return &MockPricingService_GetPricingPlans_Call{Call: _e.mock.On("GetPricingPlans", ctx, userID, filters, sorts, pagination)}
}

func (_c *MockPricingService_GetPricingPlans_Call) Run(run func(ctx context.Context, userID uint, filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination)) *MockPricingService_GetPricingPlans_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 []queryutil.CrudFilter
		if args[2] != nil {
			arg2 = args[2].([]queryutil.CrudFilter)
		}
		var arg3 []queryutil.Sort
		if args[3] != nil {
			arg3 = args[3].([]queryutil.Sort)
		}
		var arg4 queryutil.Pagination
		if args[4] != nil {
			arg4 = args[4].(queryutil.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockPricingService_GetPricingPlans_Call) Return(pricingPlans []*models.PricingPlan, n int64, err error) *MockPricingService_GetPricingPlans_Call {
	_c.Call.Return(pricingPlans, n, err)
	return _c
}

func (_c *MockPricingService_GetPricingPlans_Call) RunAndReturn(run func(ctx context.Context, userID uint, filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]*models.PricingPlan, int64, error)) *MockPricingService_GetPricingPlans_Call {
	_c.Call.Return(run)
	return _c
}

// GetUpgradeDowngradePlans provides a mock function for the type MockPricingService
func (_mock *MockPricingService) GetUpgradeDowngradePlans(ctx context.Context, currentPlanID uint, priceLineID uint) (*UpgradeDowngradePaths, error) {
	ret := _mock.Called(ctx, currentPlanID, priceLineID)

	if len(ret) == 0 {
		panic("no return value specified for GetUpgradeDowngradePlans")
	}

	var r0 *UpgradeDowngradePaths
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) (*UpgradeDowngradePaths, error)); ok {
		return returnFunc(ctx, currentPlanID, priceLineID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) *UpgradeDowngradePaths); ok {
		r0 = returnFunc(ctx, currentPlanID, priceLineID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*UpgradeDowngradePaths)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = returnFunc(ctx, currentPlanID, priceLineID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPricingService_GetUpgradeDowngradePlans_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUpgradeDowngradePlans'
type MockPricingService_GetUpgradeDowngradePlans_Call struct {
	*mock.Call
}

// GetUpgradeDowngradePlans is a helper method to define mock.On call
//   - ctx context.Context
//   - currentPlanID uint
//   - priceLineID uint
func (_e *MockPricingService_Expecter) GetUpgradeDowngradePlans(ctx interface{}, currentPlanID interface{}, priceLineID interface{}) *MockPricingService_GetUpgradeDowngradePlans_Call {
	return &MockPricingService_GetUpgradeDowngradePlans_Call{Call: _e.mock.On("GetUpgradeDowngradePlans", ctx, currentPlanID, priceLineID)}
}

func (_c *MockPricingService_GetUpgradeDowngradePlans_Call) Run(run func(ctx context.Context, currentPlanID uint, priceLineID uint)) *MockPricingService_GetUpgradeDowngradePlans_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPricingService_GetUpgradeDowngradePlans_Call) Return(upgradeDowngradePaths *UpgradeDowngradePaths, err error) *MockPricingService_GetUpgradeDowngradePlans_Call {
	_c.Call.Return(upgradeDowngradePaths, err)
	return _c
}

func (_c *MockPricingService_GetUpgradeDowngradePlans_Call) RunAndReturn(run func(ctx context.Context, currentPlanID uint, priceLineID uint) (*UpgradeDowngradePaths, error)) *MockPricingService_GetUpgradeDowngradePlans_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockPricingService
func (_mock *MockPricingService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockPricingService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockPricingService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockPricingService_Expecter) ID() *MockPricingService_ID_Call {
	return &MockPricingService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockPricingService_ID_Call) Run(run func()) *MockPricingService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPricingService_ID_Call) Return(s string) *MockPricingService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockPricingService_ID_Call) RunAndReturn(run func() string) *MockPricingService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Logger provides a mock function for the type MockPricingService
func (_mock *MockPricingService) Logger() *core.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 *core.Logger
	if returnFunc, ok := ret.Get(0).(func() *core.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Logger)
		}
	}
	return r0
}

// MockPricingService_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockPricingService_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockPricingService_Expecter) Logger() *MockPricingService_Logger_Call {
	return &MockPricingService_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockPricingService_Logger_Call) Run(run func()) *MockPricingService_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPricingService_Logger_Call) Return(logger *core.Logger) *MockPricingService_Logger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockPricingService_Logger_Call) RunAndReturn(run func() *core.Logger) *MockPricingService_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// RecordGatewaySyncError provides a mock function for the type MockPricingService
func (_mock *MockPricingService) RecordGatewaySyncError(ctx context.Context, planID uint, gatewayType string, syncErr error) error {
	ret := _mock.Called(ctx, planID, gatewayType, syncErr)

	if len(ret) == 0 {
		panic("no return value specified for RecordGatewaySyncError")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string, error) error); ok {
		r0 = returnFunc(ctx, planID, gatewayType, syncErr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPricingService_RecordGatewaySyncError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordGatewaySyncError'
type MockPricingService_RecordGatewaySyncError_Call struct {
	*mock.Call
}

// RecordGatewaySyncError is a helper method to define mock.On call
//   - ctx context.Context
//   - planID uint
//   - gatewayType string
//   - syncErr error
func (_e *MockPricingService_Expecter) RecordGatewaySyncError(ctx interface{}, planID interface{}, gatewayType interface{}, syncErr interface{}) *MockPricingService_RecordGatewaySyncError_Call {
	return &MockPricingService_RecordGatewaySyncError_Call{Call: _e.mock.On("RecordGatewaySyncError", ctx, planID, gatewayType, syncErr)}
}

func (_c *MockPricingService_RecordGatewaySyncError_Call) Run(run func(ctx context.Context, planID uint, gatewayType string, syncErr error)) *MockPricingService_RecordGatewaySyncError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 error
		if args[3] != nil {
			arg3 = args[3].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPricingService_RecordGatewaySyncError_Call) Return(err error) *MockPricingService_RecordGatewaySyncError_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPricingService_RecordGatewaySyncError_Call) RunAndReturn(run func(ctx context.Context, planID uint, gatewayType string, syncErr error) error) *MockPricingService_RecordGatewaySyncError_Call {
	_c.Call.Return(run)
	return _c
}

// RemovePlanFromPriceLine provides a mock function for the type MockPricingService
func (_mock *MockPricingService) RemovePlanFromPriceLine(ctx context.Context, priceLineID uint, planID uint) error {
	ret := _mock.Called(ctx, priceLineID, planID)

	if len(ret) == 0 {
		panic("no return value specified for RemovePlanFromPriceLine")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = returnFunc(ctx, priceLineID, planID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPricingService_RemovePlanFromPriceLine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemovePlanFromPriceLine'
type MockPricingService_RemovePlanFromPriceLine_Call struct {
	*mock.Call
}

// RemovePlanFromPriceLine is a helper method to define mock.On call
//   - ctx context.Context
//   - priceLineID uint
//   - planID uint
func (_e *MockPricingService_Expecter) RemovePlanFromPriceLine(ctx interface{}, priceLineID interface{}, planID interface{}) *MockPricingService_RemovePlanFromPriceLine_Call {
	return &MockPricingService_RemovePlanFromPriceLine_Call{Call: _e.mock.On("RemovePlanFromPriceLine", ctx, priceLineID, planID)}
}

func (_c *MockPricingService_RemovePlanFromPriceLine_Call) Run(run func(ctx context.Context, priceLineID uint, planID uint)) *MockPricingService_RemovePlanFromPriceLine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPricingService_RemovePlanFromPriceLine_Call) Return(err error) *MockPricingService_RemovePlanFromPriceLine_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPricingService_RemovePlanFromPriceLine_Call) RunAndReturn(run func(ctx context.Context, priceLineID uint, planID uint) error) *MockPricingService_RemovePlanFromPriceLine_Call {
	_c.Call.Return(run)
	return _c
}

// SetConfig provides a mock function for the type MockPricingService
func (_mock *MockPricingService) SetConfig(cfg config.Manager) {
	_mock.Called(cfg)
	return
}

// MockPricingService_SetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfig'
type MockPricingService_SetConfig_Call struct {
	*mock.Call
}

// SetConfig is a helper method to define mock.On call
//   - cfg config.Manager
func (_e *MockPricingService_Expecter) SetConfig(cfg interface{}) *MockPricingService_SetConfig_Call {
	return &MockPricingService_SetConfig_Call{Call: _e.mock.On("SetConfig", cfg)}
}

func (_c *MockPricingService_SetConfig_Call) Run(run func(cfg config.Manager)) *MockPricingService_SetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.Manager
		if args[0] != nil {
			arg0 = args[0].(config.Manager)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPricingService_SetConfig_Call) Return() *MockPricingService_SetConfig_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPricingService_SetConfig_Call) RunAndReturn(run func(cfg config.Manager)) *MockPricingService_SetConfig_Call {
	_c.Run(run)
	return _c
}

// SetContext provides a mock function for the type MockPricingService
func (_mock *MockPricingService) SetContext(ctx core.Context) {
	_mock.Called(ctx)
	return
}

// MockPricingService_SetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContext'
type MockPricingService_SetContext_Call struct {
	*mock.Call
}

// SetContext is a helper method to define mock.On call
//   - ctx core.Context
func (_e *MockPricingService_Expecter) SetContext(ctx interface{}) *MockPricingService_SetContext_Call {
	return &MockPricingService_SetContext_Call{Call: _e.mock.On("SetContext", ctx)}
}

func (_c *MockPricingService_SetContext_Call) Run(run func(ctx core.Context)) *MockPricingService_SetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.Context
		if args[0] != nil {
			arg0 = args[0].(core.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPricingService_SetContext_Call) Return() *MockPricingService_SetContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPricingService_SetContext_Call) RunAndReturn(run func(ctx core.Context)) *MockPricingService_SetContext_Call {
	_c.Run(run)
	return _c
}

// SetDB provides a mock function for the type MockPricingService
func (_mock *MockPricingService) SetDB(db *gorm.DB) {
	_mock.Called(db)
	return
}

// MockPricingService_SetDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDB'
type MockPricingService_SetDB_Call struct {
	*mock.Call
}

// SetDB is a helper method to define mock.On call
//   - db *gorm.DB
func (_e *MockPricingService_Expecter) SetDB(db interface{}) *MockPricingService_SetDB_Call {
	return &MockPricingService_SetDB_Call{Call: _e.mock.On("SetDB", db)}
}

func (_c *MockPricingService_SetDB_Call) Run(run func(db *gorm.DB)) *MockPricingService_SetDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPricingService_SetDB_Call) Return() *MockPricingService_SetDB_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPricingService_SetDB_Call) RunAndReturn(run func(db *gorm.DB)) *MockPricingService_SetDB_Call {
	_c.Run(run)
	return _c
}

// SetLogger provides a mock function for the type MockPricingService
func (_mock *MockPricingService) SetLogger(logger *core.Logger) {
	_mock.Called(logger)
	return
}

// MockPricingService_SetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLogger'
type MockPricingService_SetLogger_Call struct {
	*mock.Call
}

// SetLogger is a helper method to define mock.On call
//   - logger *core.Logger
func (_e *MockPricingService_Expecter) SetLogger(logger interface{}) *MockPricingService_SetLogger_Call {
	return &MockPricingService_SetLogger_Call{Call: _e.mock.On("SetLogger", logger)}
}

func (_c *MockPricingService_SetLogger_Call) Run(run func(logger *core.Logger)) *MockPricingService_SetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *core.Logger
		if args[0] != nil {
			arg0 = args[0].(*core.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPricingService_SetLogger_Call) Return() *MockPricingService_SetLogger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPricingService_SetLogger_Call) RunAndReturn(run func(logger *core.Logger)) *MockPricingService_SetLogger_Call {
	_c.Run(run)
	return _c
}

// UpdateGatewayProductMapping provides a mock function for the type MockPricingService
func (_mock *MockPricingService) UpdateGatewayProductMapping(ctx context.Context, id uint, mapping *models.GatewayProductMapping) error {
	ret := _mock.Called(ctx, id, mapping)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGatewayProductMapping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, *models.GatewayProductMapping) error); ok {
		r0 = returnFunc(ctx, id, mapping)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPricingService_UpdateGatewayProductMapping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGatewayProductMapping'
type MockPricingService_UpdateGatewayProductMapping_Call struct {
	*mock.Call
}

// UpdateGatewayProductMapping is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - mapping *models.GatewayProductMapping
func (_e *MockPricingService_Expecter) UpdateGatewayProductMapping(ctx interface{}, id interface{}, mapping interface{}) *MockPricingService_UpdateGatewayProductMapping_Call {
	return &MockPricingService_UpdateGatewayProductMapping_Call{Call: _e.mock.On("UpdateGatewayProductMapping", ctx, id, mapping)}
}

func (_c *MockPricingService_UpdateGatewayProductMapping_Call) Run(run func(ctx context.Context, id uint, mapping *models.GatewayProductMapping)) *MockPricingService_UpdateGatewayProductMapping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 *models.GatewayProductMapping
		if args[2] != nil {
			arg2 = args[2].(*models.GatewayProductMapping)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPricingService_UpdateGatewayProductMapping_Call) Return(err error) *MockPricingService_UpdateGatewayProductMapping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPricingService_UpdateGatewayProductMapping_Call) RunAndReturn(run func(ctx context.Context, id uint, mapping *models.GatewayProductMapping) error) *MockPricingService_UpdateGatewayProductMapping_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGatewaySyncStatus provides a mock function for the type MockPricingService
func (_mock *MockPricingService) UpdateGatewaySyncStatus(ctx context.Context, planID uint, gatewayType string, syncResult SyncResult) error {
	ret := _mock.Called(ctx, planID, gatewayType, syncResult)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGatewaySyncStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string, SyncResult) error); ok {
		r0 = returnFunc(ctx, planID, gatewayType, syncResult)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPricingService_UpdateGatewaySyncStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGatewaySyncStatus'
type MockPricingService_UpdateGatewaySyncStatus_Call struct {
	*mock.Call
}

// UpdateGatewaySyncStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - planID uint
//   - gatewayType string
//   - syncResult SyncResult
func (_e *MockPricingService_Expecter) UpdateGatewaySyncStatus(ctx interface{}, planID interface{}, gatewayType interface{}, syncResult interface{}) *MockPricingService_UpdateGatewaySyncStatus_Call {
	return &MockPricingService_UpdateGatewaySyncStatus_Call{Call: _e.mock.On("UpdateGatewaySyncStatus", ctx, planID, gatewayType, syncResult)}
}

func (_c *MockPricingService_UpdateGatewaySyncStatus_Call) Run(run func(ctx context.Context, planID uint, gatewayType string, syncResult SyncResult)) *MockPricingService_UpdateGatewaySyncStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 SyncResult
		if args[3] != nil {
			arg3 = args[3].(SyncResult)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPricingService_UpdateGatewaySyncStatus_Call) Return(err error) *MockPricingService_UpdateGatewaySyncStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPricingService_UpdateGatewaySyncStatus_Call) RunAndReturn(run func(ctx context.Context, planID uint, gatewayType string, syncResult SyncResult) error) *MockPricingService_UpdateGatewaySyncStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePlanPosition provides a mock function for the type MockPricingService
func (_mock *MockPricingService) UpdatePlanPosition(ctx context.Context, priceLineID uint, planID uint, newPosition int) error {
	ret := _mock.Called(ctx, priceLineID, planID, newPosition)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePlanPosition")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, int) error); ok {
		r0 = returnFunc(ctx, priceLineID, planID, newPosition)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPricingService_UpdatePlanPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePlanPosition'
type MockPricingService_UpdatePlanPosition_Call struct {
	*mock.Call
}

// UpdatePlanPosition is a helper method to define mock.On call
//   - ctx context.Context
//   - priceLineID uint
//   - planID uint
//   - newPosition int
func (_e *MockPricingService_Expecter) UpdatePlanPosition(ctx interface{}, priceLineID interface{}, planID interface{}, newPosition interface{}) *MockPricingService_UpdatePlanPosition_Call {
	return &MockPricingService_UpdatePlanPosition_Call{Call: _e.mock.On("UpdatePlanPosition", ctx, priceLineID, planID, newPosition)}
}

func (_c *MockPricingService_UpdatePlanPosition_Call) Run(run func(ctx context.Context, priceLineID uint, planID uint, newPosition int)) *MockPricingService_UpdatePlanPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPricingService_UpdatePlanPosition_Call) Return(err error) *MockPricingService_UpdatePlanPosition_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPricingService_UpdatePlanPosition_Call) RunAndReturn(run func(ctx context.Context, priceLineID uint, planID uint, newPosition int) error) *MockPricingService_UpdatePlanPosition_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePriceLine provides a mock function for the type MockPricingService
func (_mock *MockPricingService) UpdatePriceLine(ctx context.Context, id uint, line *models.PriceLine) error {
	ret := _mock.Called(ctx, id, line)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePriceLine")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, *models.PriceLine) error); ok {
		r0 = returnFunc(ctx, id, line)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPricingService_UpdatePriceLine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePriceLine'
type MockPricingService_UpdatePriceLine_Call struct {
	*mock.Call
}

// UpdatePriceLine is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - line *models.PriceLine
func (_e *MockPricingService_Expecter) UpdatePriceLine(ctx interface{}, id interface{}, line interface{}) *MockPricingService_UpdatePriceLine_Call {
	return &MockPricingService_UpdatePriceLine_Call{Call: _e.mock.On("UpdatePriceLine", ctx, id, line)}
}

func (_c *MockPricingService_UpdatePriceLine_Call) Run(run func(ctx context.Context, id uint, line *models.PriceLine)) *MockPricingService_UpdatePriceLine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 *models.PriceLine
		if args[2] != nil {
			arg2 = args[2].(*models.PriceLine)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPricingService_UpdatePriceLine_Call) Return(err error) *MockPricingService_UpdatePriceLine_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPricingService_UpdatePriceLine_Call) RunAndReturn(run func(ctx context.Context, id uint, line *models.PriceLine) error) *MockPricingService_UpdatePriceLine_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePricingPlan provides a mock function for the type MockPricingService
func (_mock *MockPricingService) UpdatePricingPlan(ctx context.Context, id uint, plan *models.PricingPlan) error {
	ret := _mock.Called(ctx, id, plan)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePricingPlan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, *models.PricingPlan) error); ok {
		r0 = returnFunc(ctx, id, plan)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPricingService_UpdatePricingPlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePricingPlan'
type MockPricingService_UpdatePricingPlan_Call struct {
	*mock.Call
}

// UpdatePricingPlan is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - plan *models.PricingPlan
func (_e *MockPricingService_Expecter) UpdatePricingPlan(ctx interface{}, id interface{}, plan interface{}) *MockPricingService_UpdatePricingPlan_Call {
	return &MockPricingService_UpdatePricingPlan_Call{Call: _e.mock.On("UpdatePricingPlan", ctx, id, plan)}
}

func (_c *MockPricingService_UpdatePricingPlan_Call) Run(run func(ctx context.Context, id uint, plan *models.PricingPlan)) *MockPricingService_UpdatePricingPlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 *models.PricingPlan
		if args[2] != nil {
			arg2 = args[2].(*models.PricingPlan)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPricingService_UpdatePricingPlan_Call) Return(err error) *MockPricingService_UpdatePricingPlan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPricingService_UpdatePricingPlan_Call) RunAndReturn(run func(ctx context.Context, id uint, plan *models.PricingPlan) error) *MockPricingService_UpdatePricingPlan_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePricingPlanPeriod provides a mock function for the type MockPricingService
func (_mock *MockPricingService) UpdatePricingPlanPeriod(ctx context.Context, id uint, period *models.PricingPlanPeriod) error {
	ret := _mock.Called(ctx, id, period)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePricingPlanPeriod")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, *models.PricingPlanPeriod) error); ok {
		r0 = returnFunc(ctx, id, period)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPricingService_UpdatePricingPlanPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePricingPlanPeriod'
type MockPricingService_UpdatePricingPlanPeriod_Call struct {
	*mock.Call
}

// UpdatePricingPlanPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - period *models.PricingPlanPeriod
func (_e *MockPricingService_Expecter) UpdatePricingPlanPeriod(ctx interface{}, id interface{}, period interface{}) *MockPricingService_UpdatePricingPlanPeriod_Call {
	return &MockPricingService_UpdatePricingPlanPeriod_Call{Call: _e.mock.On("UpdatePricingPlanPeriod", ctx, id, period)}
}

func (_c *MockPricingService_UpdatePricingPlanPeriod_Call) Run(run func(ctx context.Context, id uint, period *models.PricingPlanPeriod)) *MockPricingService_UpdatePricingPlanPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 *models.PricingPlanPeriod
		if args[2] != nil {
			arg2 = args[2].(*models.PricingPlanPeriod)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPricingService_UpdatePricingPlanPeriod_Call) Return(err error) *MockPricingService_UpdatePricingPlanPeriod_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPricingService_UpdatePricingPlanPeriod_Call) RunAndReturn(run func(ctx context.Context, id uint, period *models.PricingPlanPeriod) error) *MockPricingService_UpdatePricingPlanPeriod_Call {
	_c.Call.Return(run)
	return _c
}
