// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package core

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockGatewayCapabilities creates a new instance of MockGatewayCapabilities. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGatewayCapabilities(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGatewayCapabilities {
	mock := &MockGatewayCapabilities{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGatewayCapabilities is an autogenerated mock type for the GatewayCapabilities type
type MockGatewayCapabilities struct {
	mock.Mock
}

type MockGatewayCapabilities_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGatewayCapabilities) EXPECT() *MockGatewayCapabilities_Expecter {
	return &MockGatewayCapabilities_Expecter{mock: &_m.Mock}
}

// RequiredPricingFields provides a mock function for the type MockGatewayCapabilities
func (_mock *MockGatewayCapabilities) RequiredPricingFields() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RequiredPricingFields")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockGatewayCapabilities_RequiredPricingFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequiredPricingFields'
type MockGatewayCapabilities_RequiredPricingFields_Call struct {
	*mock.Call
}

// RequiredPricingFields is a helper method to define mock.On call
func (_e *MockGatewayCapabilities_Expecter) RequiredPricingFields() *MockGatewayCapabilities_RequiredPricingFields_Call {
	return &MockGatewayCapabilities_RequiredPricingFields_Call{Call: _e.mock.On("RequiredPricingFields")}
}

func (_c *MockGatewayCapabilities_RequiredPricingFields_Call) Run(run func()) *MockGatewayCapabilities_RequiredPricingFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGatewayCapabilities_RequiredPricingFields_Call) Return(strings []string) *MockGatewayCapabilities_RequiredPricingFields_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockGatewayCapabilities_RequiredPricingFields_Call) RunAndReturn(run func() []string) *MockGatewayCapabilities_RequiredPricingFields_Call {
	_c.Call.Return(run)
	return _c
}

// SupportsPlanDeletion provides a mock function for the type MockGatewayCapabilities
func (_mock *MockGatewayCapabilities) SupportsPlanDeletion() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportsPlanDeletion")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockGatewayCapabilities_SupportsPlanDeletion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportsPlanDeletion'
type MockGatewayCapabilities_SupportsPlanDeletion_Call struct {
	*mock.Call
}

// SupportsPlanDeletion is a helper method to define mock.On call
func (_e *MockGatewayCapabilities_Expecter) SupportsPlanDeletion() *MockGatewayCapabilities_SupportsPlanDeletion_Call {
	return &MockGatewayCapabilities_SupportsPlanDeletion_Call{Call: _e.mock.On("SupportsPlanDeletion")}
}

func (_c *MockGatewayCapabilities_SupportsPlanDeletion_Call) Run(run func()) *MockGatewayCapabilities_SupportsPlanDeletion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGatewayCapabilities_SupportsPlanDeletion_Call) Return(b bool) *MockGatewayCapabilities_SupportsPlanDeletion_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockGatewayCapabilities_SupportsPlanDeletion_Call) RunAndReturn(run func() bool) *MockGatewayCapabilities_SupportsPlanDeletion_Call {
	_c.Call.Return(run)
	return _c
}

// SupportsPriceUpdates provides a mock function for the type MockGatewayCapabilities
func (_mock *MockGatewayCapabilities) SupportsPriceUpdates() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportsPriceUpdates")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockGatewayCapabilities_SupportsPriceUpdates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportsPriceUpdates'
type MockGatewayCapabilities_SupportsPriceUpdates_Call struct {
	*mock.Call
}

// SupportsPriceUpdates is a helper method to define mock.On call
func (_e *MockGatewayCapabilities_Expecter) SupportsPriceUpdates() *MockGatewayCapabilities_SupportsPriceUpdates_Call {
	return &MockGatewayCapabilities_SupportsPriceUpdates_Call{Call: _e.mock.On("SupportsPriceUpdates")}
}

func (_c *MockGatewayCapabilities_SupportsPriceUpdates_Call) Run(run func()) *MockGatewayCapabilities_SupportsPriceUpdates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGatewayCapabilities_SupportsPriceUpdates_Call) Return(b bool) *MockGatewayCapabilities_SupportsPriceUpdates_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockGatewayCapabilities_SupportsPriceUpdates_Call) RunAndReturn(run func() bool) *MockGatewayCapabilities_SupportsPriceUpdates_Call {
	_c.Call.Return(run)
	return _c
}

// SupportsProductSync provides a mock function for the type MockGatewayCapabilities
func (_mock *MockGatewayCapabilities) SupportsProductSync() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportsProductSync")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockGatewayCapabilities_SupportsProductSync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportsProductSync'
type MockGatewayCapabilities_SupportsProductSync_Call struct {
	*mock.Call
}

// SupportsProductSync is a helper method to define mock.On call
func (_e *MockGatewayCapabilities_Expecter) SupportsProductSync() *MockGatewayCapabilities_SupportsProductSync_Call {
	return &MockGatewayCapabilities_SupportsProductSync_Call{Call: _e.mock.On("SupportsProductSync")}
}

func (_c *MockGatewayCapabilities_SupportsProductSync_Call) Run(run func()) *MockGatewayCapabilities_SupportsProductSync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGatewayCapabilities_SupportsProductSync_Call) Return(b bool) *MockGatewayCapabilities_SupportsProductSync_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockGatewayCapabilities_SupportsProductSync_Call) RunAndReturn(run func() bool) *MockGatewayCapabilities_SupportsProductSync_Call {
	_c.Call.Return(run)
	return _c
}
