// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package core

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBillingService creates a new instance of MockBillingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBillingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBillingService {
	mock := &MockBillingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBillingService is an autogenerated mock type for the BillingService type
type MockBillingService struct {
	mock.Mock
}

type MockBillingService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBillingService) EXPECT() *MockBillingService_Expecter {
	return &MockBillingService_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type MockBillingService
func (_mock *MockBillingService) Config() (any, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (any, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBillingService_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockBillingService_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockBillingService_Expecter) Config() *MockBillingService_Config_Call {
	return &MockBillingService_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockBillingService_Config_Call) Run(run func()) *MockBillingService_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBillingService_Config_Call) Return(v any, err error) *MockBillingService_Config_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockBillingService_Config_Call) RunAndReturn(run func() (any, error)) *MockBillingService_Config_Call {
	_c.Call.Return(run)
	return _c
}

// GetSignatureHeader provides a mock function for the type MockBillingService
func (_mock *MockBillingService) GetSignatureHeader(gatewayType string) (string, error) {
	ret := _mock.Called(gatewayType)

	if len(ret) == 0 {
		panic("no return value specified for GetSignatureHeader")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(gatewayType)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(gatewayType)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(gatewayType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBillingService_GetSignatureHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSignatureHeader'
type MockBillingService_GetSignatureHeader_Call struct {
	*mock.Call
}

// GetSignatureHeader is a helper method to define mock.On call
//   - gatewayType string
func (_e *MockBillingService_Expecter) GetSignatureHeader(gatewayType interface{}) *MockBillingService_GetSignatureHeader_Call {
	return &MockBillingService_GetSignatureHeader_Call{Call: _e.mock.On("GetSignatureHeader", gatewayType)}
}

func (_c *MockBillingService_GetSignatureHeader_Call) Run(run func(gatewayType string)) *MockBillingService_GetSignatureHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBillingService_GetSignatureHeader_Call) Return(s string, err error) *MockBillingService_GetSignatureHeader_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockBillingService_GetSignatureHeader_Call) RunAndReturn(run func(gatewayType string) (string, error)) *MockBillingService_GetSignatureHeader_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockBillingService
func (_mock *MockBillingService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockBillingService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockBillingService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockBillingService_Expecter) ID() *MockBillingService_ID_Call {
	return &MockBillingService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockBillingService_ID_Call) Run(run func()) *MockBillingService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBillingService_ID_Call) Return(s string) *MockBillingService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockBillingService_ID_Call) RunAndReturn(run func() string) *MockBillingService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessWebhook provides a mock function for the type MockBillingService
func (_mock *MockBillingService) ProcessWebhook(ctx context.Context, gatewayType string, signature string, payload []byte) error {
	ret := _mock.Called(ctx, gatewayType, signature, payload)

	if len(ret) == 0 {
		panic("no return value specified for ProcessWebhook")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []byte) error); ok {
		r0 = returnFunc(ctx, gatewayType, signature, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBillingService_ProcessWebhook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessWebhook'
type MockBillingService_ProcessWebhook_Call struct {
	*mock.Call
}

// ProcessWebhook is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayType string
//   - signature string
//   - payload []byte
func (_e *MockBillingService_Expecter) ProcessWebhook(ctx interface{}, gatewayType interface{}, signature interface{}, payload interface{}) *MockBillingService_ProcessWebhook_Call {
	return &MockBillingService_ProcessWebhook_Call{Call: _e.mock.On("ProcessWebhook", ctx, gatewayType, signature, payload)}
}

func (_c *MockBillingService_ProcessWebhook_Call) Run(run func(ctx context.Context, gatewayType string, signature string, payload []byte)) *MockBillingService_ProcessWebhook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBillingService_ProcessWebhook_Call) Return(err error) *MockBillingService_ProcessWebhook_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBillingService_ProcessWebhook_Call) RunAndReturn(run func(ctx context.Context, gatewayType string, signature string, payload []byte) error) *MockBillingService_ProcessWebhook_Call {
	_c.Call.Return(run)
	return _c
}
