// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package core

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-plugin-billing/pkg/ledger"
	"go.lumeweb.com/portal/config"
	"go.lumeweb.com/portal/core"
	"go.lumeweb.com/queryutil"
	"gorm.io/gorm"
)

// NewMockCreditService creates a new instance of MockCreditService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreditService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreditService {
	mock := &MockCreditService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreditService is an autogenerated mock type for the CreditService type
type MockCreditService struct {
	mock.Mock
}

type MockCreditService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreditService) EXPECT() *MockCreditService_Expecter {
	return &MockCreditService_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type MockCreditService
func (_mock *MockCreditService) Config() config.Manager {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 config.Manager
	if returnFunc, ok := ret.Get(0).(func() config.Manager); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.Manager)
		}
	}
	return r0
}

// MockCreditService_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockCreditService_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockCreditService_Expecter) Config() *MockCreditService_Config_Call {
	return &MockCreditService_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockCreditService_Config_Call) Run(run func()) *MockCreditService_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCreditService_Config_Call) Return(manager config.Manager) *MockCreditService_Config_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockCreditService_Config_Call) RunAndReturn(run func() config.Manager) *MockCreditService_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function for the type MockCreditService
func (_mock *MockCreditService) Context() core.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 core.Context
	if returnFunc, ok := ret.Get(0).(func() core.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Context)
		}
	}
	return r0
}

// MockCreditService_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockCreditService_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockCreditService_Expecter) Context() *MockCreditService_Context_Call {
	return &MockCreditService_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockCreditService_Context_Call) Run(run func()) *MockCreditService_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCreditService_Context_Call) Return(context core.Context) *MockCreditService_Context_Call {
	_c.Call.Return(context)
	return _c
}

func (_c *MockCreditService_Context_Call) RunAndReturn(run func() core.Context) *MockCreditService_Context_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCredit provides a mock function for the type MockCreditService
func (_mock *MockCreditService) CreateCredit(ctx context.Context, credit *ledger.Credit) error {
	ret := _mock.Called(ctx, credit)

	if len(ret) == 0 {
		panic("no return value specified for CreateCredit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ledger.Credit) error); ok {
		r0 = returnFunc(ctx, credit)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCreditService_CreateCredit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCredit'
type MockCreditService_CreateCredit_Call struct {
	*mock.Call
}

// CreateCredit is a helper method to define mock.On call
//   - ctx context.Context
//   - credit *ledger.Credit
func (_e *MockCreditService_Expecter) CreateCredit(ctx interface{}, credit interface{}) *MockCreditService_CreateCredit_Call {
	return &MockCreditService_CreateCredit_Call{Call: _e.mock.On("CreateCredit", ctx, credit)}
}

func (_c *MockCreditService_CreateCredit_Call) Run(run func(ctx context.Context, credit *ledger.Credit)) *MockCreditService_CreateCredit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ledger.Credit
		if args[1] != nil {
			arg1 = args[1].(*ledger.Credit)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreditService_CreateCredit_Call) Return(err error) *MockCreditService_CreateCredit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCreditService_CreateCredit_Call) RunAndReturn(run func(ctx context.Context, credit *ledger.Credit) error) *MockCreditService_CreateCredit_Call {
	_c.Call.Return(run)
	return _c
}

// DB provides a mock function for the type MockCreditService
func (_mock *MockCreditService) DB() *gorm.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DB")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockCreditService_DB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DB'
type MockCreditService_DB_Call struct {
	*mock.Call
}

// DB is a helper method to define mock.On call
func (_e *MockCreditService_Expecter) DB() *MockCreditService_DB_Call {
	return &MockCreditService_DB_Call{Call: _e.mock.On("DB")}
}

func (_c *MockCreditService_DB_Call) Run(run func()) *MockCreditService_DB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCreditService_DB_Call) Return(dB *gorm.DB) *MockCreditService_DB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockCreditService_DB_Call) RunAndReturn(run func() *gorm.DB) *MockCreditService_DB_Call {
	_c.Call.Return(run)
	return _c
}

// GetCredit provides a mock function for the type MockCreditService
func (_mock *MockCreditService) GetCredit(ctx context.Context, id uuid.UUID) (*ledger.Credit, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCredit")
	}

	var r0 *ledger.Credit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*ledger.Credit, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *ledger.Credit); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ledger.Credit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreditService_GetCredit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCredit'
type MockCreditService_GetCredit_Call struct {
	*mock.Call
}

// GetCredit is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCreditService_Expecter) GetCredit(ctx interface{}, id interface{}) *MockCreditService_GetCredit_Call {
	return &MockCreditService_GetCredit_Call{Call: _e.mock.On("GetCredit", ctx, id)}
}

func (_c *MockCreditService_GetCredit_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCreditService_GetCredit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreditService_GetCredit_Call) Return(credit *ledger.Credit, err error) *MockCreditService_GetCredit_Call {
	_c.Call.Return(credit, err)
	return _c
}

func (_c *MockCreditService_GetCredit_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*ledger.Credit, error)) *MockCreditService_GetCredit_Call {
	_c.Call.Return(run)
	return _c
}

// GetCreditsByReference provides a mock function for the type MockCreditService
func (_mock *MockCreditService) GetCreditsByReference(ctx context.Context, referenceID string, referenceType string) ([]ledger.Credit, error) {
	ret := _mock.Called(ctx, referenceID, referenceType)

	if len(ret) == 0 {
		panic("no return value specified for GetCreditsByReference")
	}

	var r0 []ledger.Credit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]ledger.Credit, error)); ok {
		return returnFunc(ctx, referenceID, referenceType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []ledger.Credit); ok {
		r0 = returnFunc(ctx, referenceID, referenceType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ledger.Credit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, referenceID, referenceType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreditService_GetCreditsByReference_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCreditsByReference'
type MockCreditService_GetCreditsByReference_Call struct {
	*mock.Call
}

// GetCreditsByReference is a helper method to define mock.On call
//   - ctx context.Context
//   - referenceID string
//   - referenceType string
func (_e *MockCreditService_Expecter) GetCreditsByReference(ctx interface{}, referenceID interface{}, referenceType interface{}) *MockCreditService_GetCreditsByReference_Call {
	return &MockCreditService_GetCreditsByReference_Call{Call: _e.mock.On("GetCreditsByReference", ctx, referenceID, referenceType)}
}

func (_c *MockCreditService_GetCreditsByReference_Call) Run(run func(ctx context.Context, referenceID string, referenceType string)) *MockCreditService_GetCreditsByReference_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCreditService_GetCreditsByReference_Call) Return(credits []ledger.Credit, err error) *MockCreditService_GetCreditsByReference_Call {
	_c.Call.Return(credits, err)
	return _c
}

func (_c *MockCreditService_GetCreditsByReference_Call) RunAndReturn(run func(ctx context.Context, referenceID string, referenceType string) ([]ledger.Credit, error)) *MockCreditService_GetCreditsByReference_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeletedCredits provides a mock function for the type MockCreditService
func (_mock *MockCreditService) GetDeletedCredits(ctx context.Context, userID uint64) ([]ledger.Credit, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetDeletedCredits")
	}

	var r0 []ledger.Credit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) ([]ledger.Credit, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) []ledger.Credit); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ledger.Credit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreditService_GetDeletedCredits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeletedCredits'
type MockCreditService_GetDeletedCredits_Call struct {
	*mock.Call
}

// GetDeletedCredits is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *MockCreditService_Expecter) GetDeletedCredits(ctx interface{}, userID interface{}) *MockCreditService_GetDeletedCredits_Call {
	return &MockCreditService_GetDeletedCredits_Call{Call: _e.mock.On("GetDeletedCredits", ctx, userID)}
}

func (_c *MockCreditService_GetDeletedCredits_Call) Run(run func(ctx context.Context, userID uint64)) *MockCreditService_GetDeletedCredits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreditService_GetDeletedCredits_Call) Return(credits []ledger.Credit, err error) *MockCreditService_GetDeletedCredits_Call {
	_c.Call.Return(credits, err)
	return _c
}

func (_c *MockCreditService_GetDeletedCredits_Call) RunAndReturn(run func(ctx context.Context, userID uint64) ([]ledger.Credit, error)) *MockCreditService_GetDeletedCredits_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserBalance provides a mock function for the type MockCreditService
func (_mock *MockCreditService) GetUserBalance(ctx context.Context, userID uint64) (decimal.Decimal, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBalance")
	}

	var r0 decimal.Decimal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (decimal.Decimal, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) decimal.Decimal); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(decimal.Decimal)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreditService_GetUserBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserBalance'
type MockCreditService_GetUserBalance_Call struct {
	*mock.Call
}

// GetUserBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *MockCreditService_Expecter) GetUserBalance(ctx interface{}, userID interface{}) *MockCreditService_GetUserBalance_Call {
	return &MockCreditService_GetUserBalance_Call{Call: _e.mock.On("GetUserBalance", ctx, userID)}
}

func (_c *MockCreditService_GetUserBalance_Call) Run(run func(ctx context.Context, userID uint64)) *MockCreditService_GetUserBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreditService_GetUserBalance_Call) Return(decimal1 decimal.Decimal, err error) *MockCreditService_GetUserBalance_Call {
	_c.Call.Return(decimal1, err)
	return _c
}

func (_c *MockCreditService_GetUserBalance_Call) RunAndReturn(run func(ctx context.Context, userID uint64) (decimal.Decimal, error)) *MockCreditService_GetUserBalance_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockCreditService
func (_mock *MockCreditService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCreditService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockCreditService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockCreditService_Expecter) ID() *MockCreditService_ID_Call {
	return &MockCreditService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockCreditService_ID_Call) Run(run func()) *MockCreditService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCreditService_ID_Call) Return(s string) *MockCreditService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCreditService_ID_Call) RunAndReturn(run func() string) *MockCreditService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// IssueCreditFromGateway provides a mock function for the type MockCreditService
func (_mock *MockCreditService) IssueCreditFromGateway(ctx context.Context, userID uint64, creditType string, amount decimal.Decimal, referenceType string, referenceID string, description string, createdBy uint64) error {
	ret := _mock.Called(ctx, userID, creditType, amount, referenceType, referenceID, description, createdBy)

	if len(ret) == 0 {
		panic("no return value specified for IssueCreditFromGateway")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, string, decimal.Decimal, string, string, string, uint64) error); ok {
		r0 = returnFunc(ctx, userID, creditType, amount, referenceType, referenceID, description, createdBy)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCreditService_IssueCreditFromGateway_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueCreditFromGateway'
type MockCreditService_IssueCreditFromGateway_Call struct {
	*mock.Call
}

// IssueCreditFromGateway is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - creditType string
//   - amount decimal.Decimal
//   - referenceType string
//   - referenceID string
//   - description string
//   - createdBy uint64
func (_e *MockCreditService_Expecter) IssueCreditFromGateway(ctx interface{}, userID interface{}, creditType interface{}, amount interface{}, referenceType interface{}, referenceID interface{}, description interface{}, createdBy interface{}) *MockCreditService_IssueCreditFromGateway_Call {
	return &MockCreditService_IssueCreditFromGateway_Call{Call: _e.mock.On("IssueCreditFromGateway", ctx, userID, creditType, amount, referenceType, referenceID, description, createdBy)}
}

func (_c *MockCreditService_IssueCreditFromGateway_Call) Run(run func(ctx context.Context, userID uint64, creditType string, amount decimal.Decimal, referenceType string, referenceID string, description string, createdBy uint64)) *MockCreditService_IssueCreditFromGateway_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 decimal.Decimal
		if args[3] != nil {
			arg3 = args[3].(decimal.Decimal)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 string
		if args[6] != nil {
			arg6 = args[6].(string)
		}
		var arg7 uint64
		if args[7] != nil {
			arg7 = args[7].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
		)
	})
	return _c
}

func (_c *MockCreditService_IssueCreditFromGateway_Call) Return(err error) *MockCreditService_IssueCreditFromGateway_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCreditService_IssueCreditFromGateway_Call) RunAndReturn(run func(ctx context.Context, userID uint64, creditType string, amount decimal.Decimal, referenceType string, referenceID string, description string, createdBy uint64) error) *MockCreditService_IssueCreditFromGateway_Call {
	_c.Call.Return(run)
	return _c
}

// IssueCreditWithIdempotency provides a mock function for the type MockCreditService
func (_mock *MockCreditService) IssueCreditWithIdempotency(ctx context.Context, userID uint64, creditType string, amount decimal.Decimal, referenceType string, referenceID string, description string, createdBy uint64) error {
	ret := _mock.Called(ctx, userID, creditType, amount, referenceType, referenceID, description, createdBy)

	if len(ret) == 0 {
		panic("no return value specified for IssueCreditWithIdempotency")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, string, decimal.Decimal, string, string, string, uint64) error); ok {
		r0 = returnFunc(ctx, userID, creditType, amount, referenceType, referenceID, description, createdBy)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCreditService_IssueCreditWithIdempotency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueCreditWithIdempotency'
type MockCreditService_IssueCreditWithIdempotency_Call struct {
	*mock.Call
}

// IssueCreditWithIdempotency is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - creditType string
//   - amount decimal.Decimal
//   - referenceType string
//   - referenceID string
//   - description string
//   - createdBy uint64
func (_e *MockCreditService_Expecter) IssueCreditWithIdempotency(ctx interface{}, userID interface{}, creditType interface{}, amount interface{}, referenceType interface{}, referenceID interface{}, description interface{}, createdBy interface{}) *MockCreditService_IssueCreditWithIdempotency_Call {
	return &MockCreditService_IssueCreditWithIdempotency_Call{Call: _e.mock.On("IssueCreditWithIdempotency", ctx, userID, creditType, amount, referenceType, referenceID, description, createdBy)}
}

func (_c *MockCreditService_IssueCreditWithIdempotency_Call) Run(run func(ctx context.Context, userID uint64, creditType string, amount decimal.Decimal, referenceType string, referenceID string, description string, createdBy uint64)) *MockCreditService_IssueCreditWithIdempotency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 decimal.Decimal
		if args[3] != nil {
			arg3 = args[3].(decimal.Decimal)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 string
		if args[6] != nil {
			arg6 = args[6].(string)
		}
		var arg7 uint64
		if args[7] != nil {
			arg7 = args[7].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
		)
	})
	return _c
}

func (_c *MockCreditService_IssueCreditWithIdempotency_Call) Return(err error) *MockCreditService_IssueCreditWithIdempotency_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCreditService_IssueCreditWithIdempotency_Call) RunAndReturn(run func(ctx context.Context, userID uint64, creditType string, amount decimal.Decimal, referenceType string, referenceID string, description string, createdBy uint64) error) *MockCreditService_IssueCreditWithIdempotency_Call {
	_c.Call.Return(run)
	return _c
}

// IssueUsageCredit provides a mock function for the type MockCreditService
func (_mock *MockCreditService) IssueUsageCredit(ctx context.Context, userID uint64, creditType string, amount decimal.Decimal, referenceID string, description string, createdBy uint64) error {
	ret := _mock.Called(ctx, userID, creditType, amount, referenceID, description, createdBy)

	if len(ret) == 0 {
		panic("no return value specified for IssueUsageCredit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, string, decimal.Decimal, string, string, uint64) error); ok {
		r0 = returnFunc(ctx, userID, creditType, amount, referenceID, description, createdBy)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCreditService_IssueUsageCredit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueUsageCredit'
type MockCreditService_IssueUsageCredit_Call struct {
	*mock.Call
}

// IssueUsageCredit is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - creditType string
//   - amount decimal.Decimal
//   - referenceID string
//   - description string
//   - createdBy uint64
func (_e *MockCreditService_Expecter) IssueUsageCredit(ctx interface{}, userID interface{}, creditType interface{}, amount interface{}, referenceID interface{}, description interface{}, createdBy interface{}) *MockCreditService_IssueUsageCredit_Call {
	return &MockCreditService_IssueUsageCredit_Call{Call: _e.mock.On("IssueUsageCredit", ctx, userID, creditType, amount, referenceID, description, createdBy)}
}

func (_c *MockCreditService_IssueUsageCredit_Call) Run(run func(ctx context.Context, userID uint64, creditType string, amount decimal.Decimal, referenceID string, description string, createdBy uint64)) *MockCreditService_IssueUsageCredit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 decimal.Decimal
		if args[3] != nil {
			arg3 = args[3].(decimal.Decimal)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 uint64
		if args[6] != nil {
			arg6 = args[6].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockCreditService_IssueUsageCredit_Call) Return(err error) *MockCreditService_IssueUsageCredit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCreditService_IssueUsageCredit_Call) RunAndReturn(run func(ctx context.Context, userID uint64, creditType string, amount decimal.Decimal, referenceID string, description string, createdBy uint64) error) *MockCreditService_IssueUsageCredit_Call {
	_c.Call.Return(run)
	return _c
}

// ListCredits provides a mock function for the type MockCreditService
func (_mock *MockCreditService) ListCredits(ctx context.Context, filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]ledger.Credit, int64, error) {
	ret := _mock.Called(ctx, filters, sorts, pagination)

	if len(ret) == 0 {
		panic("no return value specified for ListCredits")
	}

	var r0 []ledger.Credit
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) ([]ledger.Credit, int64, error)); ok {
		return returnFunc(ctx, filters, sorts, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) []ledger.Credit); ok {
		r0 = returnFunc(ctx, filters, sorts, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ledger.Credit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) int64); ok {
		r1 = returnFunc(ctx, filters, sorts, pagination)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) error); ok {
		r2 = returnFunc(ctx, filters, sorts, pagination)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockCreditService_ListCredits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCredits'
type MockCreditService_ListCredits_Call struct {
	*mock.Call
}

// ListCredits is a helper method to define mock.On call
//   - ctx context.Context
//   - filters []queryutil.CrudFilter
//   - sorts []queryutil.Sort
//   - pagination queryutil.Pagination
func (_e *MockCreditService_Expecter) ListCredits(ctx interface{}, filters interface{}, sorts interface{}, pagination interface{}) *MockCreditService_ListCredits_Call {
	return &MockCreditService_ListCredits_Call{Call: _e.mock.On("ListCredits", ctx, filters, sorts, pagination)}
}

func (_c *MockCreditService_ListCredits_Call) Run(run func(ctx context.Context, filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination)) *MockCreditService_ListCredits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []queryutil.CrudFilter
		if args[1] != nil {
			arg1 = args[1].([]queryutil.CrudFilter)
		}
		var arg2 []queryutil.Sort
		if args[2] != nil {
			arg2 = args[2].([]queryutil.Sort)
		}
		var arg3 queryutil.Pagination
		if args[3] != nil {
			arg3 = args[3].(queryutil.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCreditService_ListCredits_Call) Return(credits []ledger.Credit, n int64, err error) *MockCreditService_ListCredits_Call {
	_c.Call.Return(credits, n, err)
	return _c
}

func (_c *MockCreditService_ListCredits_Call) RunAndReturn(run func(ctx context.Context, filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]ledger.Credit, int64, error)) *MockCreditService_ListCredits_Call {
	_c.Call.Return(run)
	return _c
}

// Logger provides a mock function for the type MockCreditService
func (_mock *MockCreditService) Logger() *core.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 *core.Logger
	if returnFunc, ok := ret.Get(0).(func() *core.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Logger)
		}
	}
	return r0
}

// MockCreditService_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockCreditService_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockCreditService_Expecter) Logger() *MockCreditService_Logger_Call {
	return &MockCreditService_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockCreditService_Logger_Call) Run(run func()) *MockCreditService_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCreditService_Logger_Call) Return(logger *core.Logger) *MockCreditService_Logger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockCreditService_Logger_Call) RunAndReturn(run func() *core.Logger) *MockCreditService_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeDeletedCredits provides a mock function for the type MockCreditService
func (_mock *MockCreditService) PurgeDeletedCredits(ctx context.Context, olderThan time.Duration) (int, error) {
	ret := _mock.Called(ctx, olderThan)

	if len(ret) == 0 {
		panic("no return value specified for PurgeDeletedCredits")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration) (int, error)); ok {
		return returnFunc(ctx, olderThan)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration) int); ok {
		r0 = returnFunc(ctx, olderThan)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Duration) error); ok {
		r1 = returnFunc(ctx, olderThan)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreditService_PurgeDeletedCredits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeDeletedCredits'
type MockCreditService_PurgeDeletedCredits_Call struct {
	*mock.Call
}

// PurgeDeletedCredits is a helper method to define mock.On call
//   - ctx context.Context
//   - olderThan time.Duration
func (_e *MockCreditService_Expecter) PurgeDeletedCredits(ctx interface{}, olderThan interface{}) *MockCreditService_PurgeDeletedCredits_Call {
	return &MockCreditService_PurgeDeletedCredits_Call{Call: _e.mock.On("PurgeDeletedCredits", ctx, olderThan)}
}

func (_c *MockCreditService_PurgeDeletedCredits_Call) Run(run func(ctx context.Context, olderThan time.Duration)) *MockCreditService_PurgeDeletedCredits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreditService_PurgeDeletedCredits_Call) Return(n int, err error) *MockCreditService_PurgeDeletedCredits_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockCreditService_PurgeDeletedCredits_Call) RunAndReturn(run func(ctx context.Context, olderThan time.Duration) (int, error)) *MockCreditService_PurgeDeletedCredits_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreCredit provides a mock function for the type MockCreditService
func (_mock *MockCreditService) RestoreCredit(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RestoreCredit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCreditService_RestoreCredit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreCredit'
type MockCreditService_RestoreCredit_Call struct {
	*mock.Call
}

// RestoreCredit is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCreditService_Expecter) RestoreCredit(ctx interface{}, id interface{}) *MockCreditService_RestoreCredit_Call {
	return &MockCreditService_RestoreCredit_Call{Call: _e.mock.On("RestoreCredit", ctx, id)}
}

func (_c *MockCreditService_RestoreCredit_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCreditService_RestoreCredit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreditService_RestoreCredit_Call) Return(err error) *MockCreditService_RestoreCredit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCreditService_RestoreCredit_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockCreditService_RestoreCredit_Call {
	_c.Call.Return(run)
	return _c
}

// SetConfig provides a mock function for the type MockCreditService
func (_mock *MockCreditService) SetConfig(cfg config.Manager) {
	_mock.Called(cfg)
	return
}

// MockCreditService_SetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfig'
type MockCreditService_SetConfig_Call struct {
	*mock.Call
}

// SetConfig is a helper method to define mock.On call
//   - cfg config.Manager
func (_e *MockCreditService_Expecter) SetConfig(cfg interface{}) *MockCreditService_SetConfig_Call {
	return &MockCreditService_SetConfig_Call{Call: _e.mock.On("SetConfig", cfg)}
}

func (_c *MockCreditService_SetConfig_Call) Run(run func(cfg config.Manager)) *MockCreditService_SetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.Manager
		if args[0] != nil {
			arg0 = args[0].(config.Manager)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCreditService_SetConfig_Call) Return() *MockCreditService_SetConfig_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCreditService_SetConfig_Call) RunAndReturn(run func(cfg config.Manager)) *MockCreditService_SetConfig_Call {
	_c.Run(run)
	return _c
}

// SetContext provides a mock function for the type MockCreditService
func (_mock *MockCreditService) SetContext(ctx core.Context) {
	_mock.Called(ctx)
	return
}

// MockCreditService_SetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContext'
type MockCreditService_SetContext_Call struct {
	*mock.Call
}

// SetContext is a helper method to define mock.On call
//   - ctx core.Context
func (_e *MockCreditService_Expecter) SetContext(ctx interface{}) *MockCreditService_SetContext_Call {
	return &MockCreditService_SetContext_Call{Call: _e.mock.On("SetContext", ctx)}
}

func (_c *MockCreditService_SetContext_Call) Run(run func(ctx core.Context)) *MockCreditService_SetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.Context
		if args[0] != nil {
			arg0 = args[0].(core.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCreditService_SetContext_Call) Return() *MockCreditService_SetContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCreditService_SetContext_Call) RunAndReturn(run func(ctx core.Context)) *MockCreditService_SetContext_Call {
	_c.Run(run)
	return _c
}

// SetDB provides a mock function for the type MockCreditService
func (_mock *MockCreditService) SetDB(db *gorm.DB) {
	_mock.Called(db)
	return
}

// MockCreditService_SetDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDB'
type MockCreditService_SetDB_Call struct {
	*mock.Call
}

// SetDB is a helper method to define mock.On call
//   - db *gorm.DB
func (_e *MockCreditService_Expecter) SetDB(db interface{}) *MockCreditService_SetDB_Call {
	return &MockCreditService_SetDB_Call{Call: _e.mock.On("SetDB", db)}
}

func (_c *MockCreditService_SetDB_Call) Run(run func(db *gorm.DB)) *MockCreditService_SetDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCreditService_SetDB_Call) Return() *MockCreditService_SetDB_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCreditService_SetDB_Call) RunAndReturn(run func(db *gorm.DB)) *MockCreditService_SetDB_Call {
	_c.Run(run)
	return _c
}

// SetLogger provides a mock function for the type MockCreditService
func (_mock *MockCreditService) SetLogger(logger *core.Logger) {
	_mock.Called(logger)
	return
}

// MockCreditService_SetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLogger'
type MockCreditService_SetLogger_Call struct {
	*mock.Call
}

// SetLogger is a helper method to define mock.On call
//   - logger *core.Logger
func (_e *MockCreditService_Expecter) SetLogger(logger interface{}) *MockCreditService_SetLogger_Call {
	return &MockCreditService_SetLogger_Call{Call: _e.mock.On("SetLogger", logger)}
}

func (_c *MockCreditService_SetLogger_Call) Run(run func(logger *core.Logger)) *MockCreditService_SetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *core.Logger
		if args[0] != nil {
			arg0 = args[0].(*core.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCreditService_SetLogger_Call) Return() *MockCreditService_SetLogger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCreditService_SetLogger_Call) RunAndReturn(run func(logger *core.Logger)) *MockCreditService_SetLogger_Call {
	_c.Run(run)
	return _c
}

// SoftDeleteCredit provides a mock function for the type MockCreditService
func (_mock *MockCreditService) SoftDeleteCredit(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteCredit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCreditService_SoftDeleteCredit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDeleteCredit'
type MockCreditService_SoftDeleteCredit_Call struct {
	*mock.Call
}

// SoftDeleteCredit is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCreditService_Expecter) SoftDeleteCredit(ctx interface{}, id interface{}) *MockCreditService_SoftDeleteCredit_Call {
	return &MockCreditService_SoftDeleteCredit_Call{Call: _e.mock.On("SoftDeleteCredit", ctx, id)}
}

func (_c *MockCreditService_SoftDeleteCredit_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCreditService_SoftDeleteCredit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreditService_SoftDeleteCredit_Call) Return(err error) *MockCreditService_SoftDeleteCredit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCreditService_SoftDeleteCredit_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockCreditService_SoftDeleteCredit_Call {
	_c.Call.Return(run)
	return _c
}
