// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package core

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionStatusProvider creates a new instance of MockSessionStatusProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionStatusProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionStatusProvider {
	mock := &MockSessionStatusProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionStatusProvider is an autogenerated mock type for the SessionStatusProvider type
type MockSessionStatusProvider struct {
	mock.Mock
}

type MockSessionStatusProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionStatusProvider) EXPECT() *MockSessionStatusProvider_Expecter {
	return &MockSessionStatusProvider_Expecter{mock: &_m.Mock}
}

// GetSessionStatus provides a mock function for the type MockSessionStatusProvider
func (_mock *MockSessionStatusProvider) GetSessionStatus(ctx context.Context, sessionID string) (*SessionStatus, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionStatus")
	}

	var r0 *SessionStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*SessionStatus, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *SessionStatus); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SessionStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionStatusProvider_GetSessionStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionStatus'
type MockSessionStatusProvider_GetSessionStatus_Call struct {
	*mock.Call
}

// GetSessionStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockSessionStatusProvider_Expecter) GetSessionStatus(ctx interface{}, sessionID interface{}) *MockSessionStatusProvider_GetSessionStatus_Call {
	return &MockSessionStatusProvider_GetSessionStatus_Call{Call: _e.mock.On("GetSessionStatus", ctx, sessionID)}
}

func (_c *MockSessionStatusProvider_GetSessionStatus_Call) Run(run func(ctx context.Context, sessionID string)) *MockSessionStatusProvider_GetSessionStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionStatusProvider_GetSessionStatus_Call) Return(sessionStatus *SessionStatus, err error) *MockSessionStatusProvider_GetSessionStatus_Call {
	_c.Call.Return(sessionStatus, err)
	return _c
}

func (_c *MockSessionStatusProvider_GetSessionStatus_Call) RunAndReturn(run func(ctx context.Context, sessionID string) (*SessionStatus, error)) *MockSessionStatusProvider_GetSessionStatus_Call {
	_c.Call.Return(run)
	return _c
}
