// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package core

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockGatewaySync creates a new instance of MockGatewaySync. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGatewaySync(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGatewaySync {
	mock := &MockGatewaySync{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGatewaySync is an autogenerated mock type for the GatewaySync type
type MockGatewaySync struct {
	mock.Mock
}

type MockGatewaySync_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGatewaySync) EXPECT() *MockGatewaySync_Expecter {
	return &MockGatewaySync_Expecter{mock: &_m.Mock}
}

// RequiredPricingFields provides a mock function for the type MockGatewaySync
func (_mock *MockGatewaySync) RequiredPricingFields() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RequiredPricingFields")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockGatewaySync_RequiredPricingFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequiredPricingFields'
type MockGatewaySync_RequiredPricingFields_Call struct {
	*mock.Call
}

// RequiredPricingFields is a helper method to define mock.On call
func (_e *MockGatewaySync_Expecter) RequiredPricingFields() *MockGatewaySync_RequiredPricingFields_Call {
	return &MockGatewaySync_RequiredPricingFields_Call{Call: _e.mock.On("RequiredPricingFields")}
}

func (_c *MockGatewaySync_RequiredPricingFields_Call) Run(run func()) *MockGatewaySync_RequiredPricingFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGatewaySync_RequiredPricingFields_Call) Return(strings []string) *MockGatewaySync_RequiredPricingFields_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockGatewaySync_RequiredPricingFields_Call) RunAndReturn(run func() []string) *MockGatewaySync_RequiredPricingFields_Call {
	_c.Call.Return(run)
	return _c
}

// SupportsPlanDeletion provides a mock function for the type MockGatewaySync
func (_mock *MockGatewaySync) SupportsPlanDeletion() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportsPlanDeletion")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockGatewaySync_SupportsPlanDeletion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportsPlanDeletion'
type MockGatewaySync_SupportsPlanDeletion_Call struct {
	*mock.Call
}

// SupportsPlanDeletion is a helper method to define mock.On call
func (_e *MockGatewaySync_Expecter) SupportsPlanDeletion() *MockGatewaySync_SupportsPlanDeletion_Call {
	return &MockGatewaySync_SupportsPlanDeletion_Call{Call: _e.mock.On("SupportsPlanDeletion")}
}

func (_c *MockGatewaySync_SupportsPlanDeletion_Call) Run(run func()) *MockGatewaySync_SupportsPlanDeletion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGatewaySync_SupportsPlanDeletion_Call) Return(b bool) *MockGatewaySync_SupportsPlanDeletion_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockGatewaySync_SupportsPlanDeletion_Call) RunAndReturn(run func() bool) *MockGatewaySync_SupportsPlanDeletion_Call {
	_c.Call.Return(run)
	return _c
}

// SupportsPriceUpdates provides a mock function for the type MockGatewaySync
func (_mock *MockGatewaySync) SupportsPriceUpdates() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportsPriceUpdates")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockGatewaySync_SupportsPriceUpdates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportsPriceUpdates'
type MockGatewaySync_SupportsPriceUpdates_Call struct {
	*mock.Call
}

// SupportsPriceUpdates is a helper method to define mock.On call
func (_e *MockGatewaySync_Expecter) SupportsPriceUpdates() *MockGatewaySync_SupportsPriceUpdates_Call {
	return &MockGatewaySync_SupportsPriceUpdates_Call{Call: _e.mock.On("SupportsPriceUpdates")}
}

func (_c *MockGatewaySync_SupportsPriceUpdates_Call) Run(run func()) *MockGatewaySync_SupportsPriceUpdates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGatewaySync_SupportsPriceUpdates_Call) Return(b bool) *MockGatewaySync_SupportsPriceUpdates_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockGatewaySync_SupportsPriceUpdates_Call) RunAndReturn(run func() bool) *MockGatewaySync_SupportsPriceUpdates_Call {
	_c.Call.Return(run)
	return _c
}

// SupportsProductSync provides a mock function for the type MockGatewaySync
func (_mock *MockGatewaySync) SupportsProductSync() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportsProductSync")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockGatewaySync_SupportsProductSync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportsProductSync'
type MockGatewaySync_SupportsProductSync_Call struct {
	*mock.Call
}

// SupportsProductSync is a helper method to define mock.On call
func (_e *MockGatewaySync_Expecter) SupportsProductSync() *MockGatewaySync_SupportsProductSync_Call {
	return &MockGatewaySync_SupportsProductSync_Call{Call: _e.mock.On("SupportsProductSync")}
}

func (_c *MockGatewaySync_SupportsProductSync_Call) Run(run func()) *MockGatewaySync_SupportsProductSync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGatewaySync_SupportsProductSync_Call) Return(b bool) *MockGatewaySync_SupportsProductSync_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockGatewaySync_SupportsProductSync_Call) RunAndReturn(run func() bool) *MockGatewaySync_SupportsProductSync_Call {
	_c.Call.Return(run)
	return _c
}

// SyncPlan provides a mock function for the type MockGatewaySync
func (_mock *MockGatewaySync) SyncPlan(ctx context.Context, plan *PricingPlanInfo) (*SyncResult, error) {
	ret := _mock.Called(ctx, plan)

	if len(ret) == 0 {
		panic("no return value specified for SyncPlan")
	}

	var r0 *SyncResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *PricingPlanInfo) (*SyncResult, error)); ok {
		return returnFunc(ctx, plan)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *PricingPlanInfo) *SyncResult); ok {
		r0 = returnFunc(ctx, plan)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SyncResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *PricingPlanInfo) error); ok {
		r1 = returnFunc(ctx, plan)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGatewaySync_SyncPlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncPlan'
type MockGatewaySync_SyncPlan_Call struct {
	*mock.Call
}

// SyncPlan is a helper method to define mock.On call
//   - ctx context.Context
//   - plan *PricingPlanInfo
func (_e *MockGatewaySync_Expecter) SyncPlan(ctx interface{}, plan interface{}) *MockGatewaySync_SyncPlan_Call {
	return &MockGatewaySync_SyncPlan_Call{Call: _e.mock.On("SyncPlan", ctx, plan)}
}

func (_c *MockGatewaySync_SyncPlan_Call) Run(run func(ctx context.Context, plan *PricingPlanInfo)) *MockGatewaySync_SyncPlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *PricingPlanInfo
		if args[1] != nil {
			arg1 = args[1].(*PricingPlanInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGatewaySync_SyncPlan_Call) Return(syncResult *SyncResult, err error) *MockGatewaySync_SyncPlan_Call {
	_c.Call.Return(syncResult, err)
	return _c
}

func (_c *MockGatewaySync_SyncPlan_Call) RunAndReturn(run func(ctx context.Context, plan *PricingPlanInfo) (*SyncResult, error)) *MockGatewaySync_SyncPlan_Call {
	_c.Call.Return(run)
	return _c
}
