// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package core

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBillingService creates a new instance of MockBillingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBillingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBillingService {
	mock := &MockBillingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBillingService is an autogenerated mock type for the BillingService type
type MockBillingService struct {
	mock.Mock
}

type MockBillingService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBillingService) EXPECT() *MockBillingService_Expecter {
	return &MockBillingService_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type MockBillingService
func (_mock *MockBillingService) Config() (any, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (any, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBillingService_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockBillingService_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockBillingService_Expecter) Config() *MockBillingService_Config_Call {
	return &MockBillingService_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockBillingService_Config_Call) Run(run func()) *MockBillingService_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBillingService_Config_Call) Return(v any, err error) *MockBillingService_Config_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockBillingService_Config_Call) RunAndReturn(run func() (any, error)) *MockBillingService_Config_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrUpdateSubscriber provides a mock function for the type MockBillingService
func (_mock *MockBillingService) CreateOrUpdateSubscriber(userID uint, gatewayType string, gatewayID string, isActive bool, planID *uint) error {
	ret := _mock.Called(userID, gatewayType, gatewayID, isActive, planID)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrUpdateSubscriber")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint, string, string, bool, *uint) error); ok {
		r0 = returnFunc(userID, gatewayType, gatewayID, isActive, planID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBillingService_CreateOrUpdateSubscriber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrUpdateSubscriber'
type MockBillingService_CreateOrUpdateSubscriber_Call struct {
	*mock.Call
}

// CreateOrUpdateSubscriber is a helper method to define mock.On call
//   - userID uint
//   - gatewayType string
//   - gatewayID string
//   - isActive bool
//   - planID *uint
func (_e *MockBillingService_Expecter) CreateOrUpdateSubscriber(userID interface{}, gatewayType interface{}, gatewayID interface{}, isActive interface{}, planID interface{}) *MockBillingService_CreateOrUpdateSubscriber_Call {
	return &MockBillingService_CreateOrUpdateSubscriber_Call{Call: _e.mock.On("CreateOrUpdateSubscriber", userID, gatewayType, gatewayID, isActive, planID)}
}

func (_c *MockBillingService_CreateOrUpdateSubscriber_Call) Run(run func(userID uint, gatewayType string, gatewayID string, isActive bool, planID *uint)) *MockBillingService_CreateOrUpdateSubscriber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 *uint
		if args[4] != nil {
			arg4 = args[4].(*uint)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockBillingService_CreateOrUpdateSubscriber_Call) Return(err error) *MockBillingService_CreateOrUpdateSubscriber_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBillingService_CreateOrUpdateSubscriber_Call) RunAndReturn(run func(userID uint, gatewayType string, gatewayID string, isActive bool, planID *uint) error) *MockBillingService_CreateOrUpdateSubscriber_Call {
	_c.Call.Return(run)
	return _c
}

// DeactivateSubscriber provides a mock function for the type MockBillingService
func (_mock *MockBillingService) DeactivateSubscriber(userID uint, gatewayType string) error {
	ret := _mock.Called(userID, gatewayType)

	if len(ret) == 0 {
		panic("no return value specified for DeactivateSubscriber")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint, string) error); ok {
		r0 = returnFunc(userID, gatewayType)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBillingService_DeactivateSubscriber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeactivateSubscriber'
type MockBillingService_DeactivateSubscriber_Call struct {
	*mock.Call
}

// DeactivateSubscriber is a helper method to define mock.On call
//   - userID uint
//   - gatewayType string
func (_e *MockBillingService_Expecter) DeactivateSubscriber(userID interface{}, gatewayType interface{}) *MockBillingService_DeactivateSubscriber_Call {
	return &MockBillingService_DeactivateSubscriber_Call{Call: _e.mock.On("DeactivateSubscriber", userID, gatewayType)}
}

func (_c *MockBillingService_DeactivateSubscriber_Call) Run(run func(userID uint, gatewayType string)) *MockBillingService_DeactivateSubscriber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBillingService_DeactivateSubscriber_Call) Return(err error) *MockBillingService_DeactivateSubscriber_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBillingService_DeactivateSubscriber_Call) RunAndReturn(run func(userID uint, gatewayType string) error) *MockBillingService_DeactivateSubscriber_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveSubscriber provides a mock function for the type MockBillingService
func (_mock *MockBillingService) GetActiveSubscriber(userID uint, gatewayType string) (*Subscriber, error) {
	ret := _mock.Called(userID, gatewayType)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveSubscriber")
	}

	var r0 *Subscriber
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, string) (*Subscriber, error)); ok {
		return returnFunc(userID, gatewayType)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, string) *Subscriber); ok {
		r0 = returnFunc(userID, gatewayType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Subscriber)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint, string) error); ok {
		r1 = returnFunc(userID, gatewayType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBillingService_GetActiveSubscriber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveSubscriber'
type MockBillingService_GetActiveSubscriber_Call struct {
	*mock.Call
}

// GetActiveSubscriber is a helper method to define mock.On call
//   - userID uint
//   - gatewayType string
func (_e *MockBillingService_Expecter) GetActiveSubscriber(userID interface{}, gatewayType interface{}) *MockBillingService_GetActiveSubscriber_Call {
	return &MockBillingService_GetActiveSubscriber_Call{Call: _e.mock.On("GetActiveSubscriber", userID, gatewayType)}
}

func (_c *MockBillingService_GetActiveSubscriber_Call) Run(run func(userID uint, gatewayType string)) *MockBillingService_GetActiveSubscriber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBillingService_GetActiveSubscriber_Call) Return(v *Subscriber, err error) *MockBillingService_GetActiveSubscriber_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockBillingService_GetActiveSubscriber_Call) RunAndReturn(run func(userID uint, gatewayType string) (*Subscriber, error)) *MockBillingService_GetActiveSubscriber_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveSubscribersByGateway provides a mock function for the type MockBillingService
func (_mock *MockBillingService) GetActiveSubscribersByGateway(gatewayType string) ([]Subscriber, error) {
	ret := _mock.Called(gatewayType)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveSubscribersByGateway")
	}

	var r0 []Subscriber
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]Subscriber, error)); ok {
		return returnFunc(gatewayType)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []Subscriber); ok {
		r0 = returnFunc(gatewayType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Subscriber)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(gatewayType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBillingService_GetActiveSubscribersByGateway_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveSubscribersByGateway'
type MockBillingService_GetActiveSubscribersByGateway_Call struct {
	*mock.Call
}

// GetActiveSubscribersByGateway is a helper method to define mock.On call
//   - gatewayType string
func (_e *MockBillingService_Expecter) GetActiveSubscribersByGateway(gatewayType interface{}) *MockBillingService_GetActiveSubscribersByGateway_Call {
	return &MockBillingService_GetActiveSubscribersByGateway_Call{Call: _e.mock.On("GetActiveSubscribersByGateway", gatewayType)}
}

func (_c *MockBillingService_GetActiveSubscribersByGateway_Call) Run(run func(gatewayType string)) *MockBillingService_GetActiveSubscribersByGateway_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBillingService_GetActiveSubscribersByGateway_Call) Return(vs []Subscriber, err error) *MockBillingService_GetActiveSubscribersByGateway_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockBillingService_GetActiveSubscribersByGateway_Call) RunAndReturn(run func(gatewayType string) ([]Subscriber, error)) *MockBillingService_GetActiveSubscribersByGateway_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveSubscription provides a mock function for the type MockBillingService
func (_mock *MockBillingService) GetActiveSubscription(userID uint) (*Subscriber, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveSubscription")
	}

	var r0 *Subscriber
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) (*Subscriber, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) *Subscriber); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Subscriber)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBillingService_GetActiveSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveSubscription'
type MockBillingService_GetActiveSubscription_Call struct {
	*mock.Call
}

// GetActiveSubscription is a helper method to define mock.On call
//   - userID uint
func (_e *MockBillingService_Expecter) GetActiveSubscription(userID interface{}) *MockBillingService_GetActiveSubscription_Call {
	return &MockBillingService_GetActiveSubscription_Call{Call: _e.mock.On("GetActiveSubscription", userID)}
}

func (_c *MockBillingService_GetActiveSubscription_Call) Run(run func(userID uint)) *MockBillingService_GetActiveSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBillingService_GetActiveSubscription_Call) Return(v *Subscriber, err error) *MockBillingService_GetActiveSubscription_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockBillingService_GetActiveSubscription_Call) RunAndReturn(run func(userID uint) (*Subscriber, error)) *MockBillingService_GetActiveSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// GetGateway provides a mock function for the type MockBillingService
func (_mock *MockBillingService) GetGateway(gatewayType string) (PaymentGateway, error) {
	ret := _mock.Called(gatewayType)

	if len(ret) == 0 {
		panic("no return value specified for GetGateway")
	}

	var r0 PaymentGateway
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (PaymentGateway, error)); ok {
		return returnFunc(gatewayType)
	}
	if returnFunc, ok := ret.Get(0).(func(string) PaymentGateway); ok {
		r0 = returnFunc(gatewayType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(PaymentGateway)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(gatewayType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBillingService_GetGateway_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGateway'
type MockBillingService_GetGateway_Call struct {
	*mock.Call
}

// GetGateway is a helper method to define mock.On call
//   - gatewayType string
func (_e *MockBillingService_Expecter) GetGateway(gatewayType interface{}) *MockBillingService_GetGateway_Call {
	return &MockBillingService_GetGateway_Call{Call: _e.mock.On("GetGateway", gatewayType)}
}

func (_c *MockBillingService_GetGateway_Call) Run(run func(gatewayType string)) *MockBillingService_GetGateway_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBillingService_GetGateway_Call) Return(paymentGateway PaymentGateway, err error) *MockBillingService_GetGateway_Call {
	_c.Call.Return(paymentGateway, err)
	return _c
}

func (_c *MockBillingService_GetGateway_Call) RunAndReturn(run func(gatewayType string) (PaymentGateway, error)) *MockBillingService_GetGateway_Call {
	_c.Call.Return(run)
	return _c
}

// GetSignatureHeader provides a mock function for the type MockBillingService
func (_mock *MockBillingService) GetSignatureHeader(gatewayType string) (string, error) {
	ret := _mock.Called(gatewayType)

	if len(ret) == 0 {
		panic("no return value specified for GetSignatureHeader")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(gatewayType)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(gatewayType)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(gatewayType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBillingService_GetSignatureHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSignatureHeader'
type MockBillingService_GetSignatureHeader_Call struct {
	*mock.Call
}

// GetSignatureHeader is a helper method to define mock.On call
//   - gatewayType string
func (_e *MockBillingService_Expecter) GetSignatureHeader(gatewayType interface{}) *MockBillingService_GetSignatureHeader_Call {
	return &MockBillingService_GetSignatureHeader_Call{Call: _e.mock.On("GetSignatureHeader", gatewayType)}
}

func (_c *MockBillingService_GetSignatureHeader_Call) Run(run func(gatewayType string)) *MockBillingService_GetSignatureHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBillingService_GetSignatureHeader_Call) Return(s string, err error) *MockBillingService_GetSignatureHeader_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockBillingService_GetSignatureHeader_Call) RunAndReturn(run func(gatewayType string) (string, error)) *MockBillingService_GetSignatureHeader_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockBillingService
func (_mock *MockBillingService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockBillingService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockBillingService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockBillingService_Expecter) ID() *MockBillingService_ID_Call {
	return &MockBillingService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockBillingService_ID_Call) Run(run func()) *MockBillingService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBillingService_ID_Call) Return(s string) *MockBillingService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockBillingService_ID_Call) RunAndReturn(run func() string) *MockBillingService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// IsUserActiveSubscriber provides a mock function for the type MockBillingService
func (_mock *MockBillingService) IsUserActiveSubscriber(userID uint) (bool, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for IsUserActiveSubscriber")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) (bool, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) bool); ok {
		r0 = returnFunc(userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBillingService_IsUserActiveSubscriber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsUserActiveSubscriber'
type MockBillingService_IsUserActiveSubscriber_Call struct {
	*mock.Call
}

// IsUserActiveSubscriber is a helper method to define mock.On call
//   - userID uint
func (_e *MockBillingService_Expecter) IsUserActiveSubscriber(userID interface{}) *MockBillingService_IsUserActiveSubscriber_Call {
	return &MockBillingService_IsUserActiveSubscriber_Call{Call: _e.mock.On("IsUserActiveSubscriber", userID)}
}

func (_c *MockBillingService_IsUserActiveSubscriber_Call) Run(run func(userID uint)) *MockBillingService_IsUserActiveSubscriber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBillingService_IsUserActiveSubscriber_Call) Return(b bool, err error) *MockBillingService_IsUserActiveSubscriber_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockBillingService_IsUserActiveSubscriber_Call) RunAndReturn(run func(userID uint) (bool, error)) *MockBillingService_IsUserActiveSubscriber_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessWebhook provides a mock function for the type MockBillingService
func (_mock *MockBillingService) ProcessWebhook(ctx context.Context, gatewayType string, signature string, payload []byte) error {
	ret := _mock.Called(ctx, gatewayType, signature, payload)

	if len(ret) == 0 {
		panic("no return value specified for ProcessWebhook")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []byte) error); ok {
		r0 = returnFunc(ctx, gatewayType, signature, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBillingService_ProcessWebhook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessWebhook'
type MockBillingService_ProcessWebhook_Call struct {
	*mock.Call
}

// ProcessWebhook is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayType string
//   - signature string
//   - payload []byte
func (_e *MockBillingService_Expecter) ProcessWebhook(ctx interface{}, gatewayType interface{}, signature interface{}, payload interface{}) *MockBillingService_ProcessWebhook_Call {
	return &MockBillingService_ProcessWebhook_Call{Call: _e.mock.On("ProcessWebhook", ctx, gatewayType, signature, payload)}
}

func (_c *MockBillingService_ProcessWebhook_Call) Run(run func(ctx context.Context, gatewayType string, signature string, payload []byte)) *MockBillingService_ProcessWebhook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBillingService_ProcessWebhook_Call) Return(err error) *MockBillingService_ProcessWebhook_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBillingService_ProcessWebhook_Call) RunAndReturn(run func(ctx context.Context, gatewayType string, signature string, payload []byte) error) *MockBillingService_ProcessWebhook_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterGateway provides a mock function for the type MockBillingService
func (_mock *MockBillingService) RegisterGateway(gateway PaymentGateway) error {
	ret := _mock.Called(gateway)

	if len(ret) == 0 {
		panic("no return value specified for RegisterGateway")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(PaymentGateway) error); ok {
		r0 = returnFunc(gateway)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBillingService_RegisterGateway_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterGateway'
type MockBillingService_RegisterGateway_Call struct {
	*mock.Call
}

// RegisterGateway is a helper method to define mock.On call
//   - gateway PaymentGateway
func (_e *MockBillingService_Expecter) RegisterGateway(gateway interface{}) *MockBillingService_RegisterGateway_Call {
	return &MockBillingService_RegisterGateway_Call{Call: _e.mock.On("RegisterGateway", gateway)}
}

func (_c *MockBillingService_RegisterGateway_Call) Run(run func(gateway PaymentGateway)) *MockBillingService_RegisterGateway_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 PaymentGateway
		if args[0] != nil {
			arg0 = args[0].(PaymentGateway)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBillingService_RegisterGateway_Call) Return(err error) *MockBillingService_RegisterGateway_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBillingService_RegisterGateway_Call) RunAndReturn(run func(gateway PaymentGateway) error) *MockBillingService_RegisterGateway_Call {
	_c.Call.Return(run)
	return _c
}
