// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package core

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSubscriptionManager creates a new instance of MockSubscriptionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriptionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriptionManager {
	mock := &MockSubscriptionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSubscriptionManager is an autogenerated mock type for the SubscriptionManager type
type MockSubscriptionManager struct {
	mock.Mock
}

type MockSubscriptionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscriptionManager) EXPECT() *MockSubscriptionManager_Expecter {
	return &MockSubscriptionManager_Expecter{mock: &_m.Mock}
}

// GetManagementInfo provides a mock function for the type MockSubscriptionManager
func (_mock *MockSubscriptionManager) GetManagementInfo(ctx context.Context, userID uint) (*ManagementCapabilities, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetManagementInfo")
	}

	var r0 *ManagementCapabilities
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*ManagementCapabilities, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *ManagementCapabilities); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ManagementCapabilities)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriptionManager_GetManagementInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetManagementInfo'
type MockSubscriptionManager_GetManagementInfo_Call struct {
	*mock.Call
}

// GetManagementInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockSubscriptionManager_Expecter) GetManagementInfo(ctx interface{}, userID interface{}) *MockSubscriptionManager_GetManagementInfo_Call {
	return &MockSubscriptionManager_GetManagementInfo_Call{Call: _e.mock.On("GetManagementInfo", ctx, userID)}
}

func (_c *MockSubscriptionManager_GetManagementInfo_Call) Run(run func(ctx context.Context, userID uint)) *MockSubscriptionManager_GetManagementInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubscriptionManager_GetManagementInfo_Call) Return(managementCapabilities *ManagementCapabilities, err error) *MockSubscriptionManager_GetManagementInfo_Call {
	_c.Call.Return(managementCapabilities, err)
	return _c
}

func (_c *MockSubscriptionManager_GetManagementInfo_Call) RunAndReturn(run func(ctx context.Context, userID uint) (*ManagementCapabilities, error)) *MockSubscriptionManager_GetManagementInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetManagementURL provides a mock function for the type MockSubscriptionManager
func (_mock *MockSubscriptionManager) GetManagementURL(ctx context.Context, userID uint, operation ManagementOperation) (*ManagementResult, error) {
	ret := _mock.Called(ctx, userID, operation)

	if len(ret) == 0 {
		panic("no return value specified for GetManagementURL")
	}

	var r0 *ManagementResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, ManagementOperation) (*ManagementResult, error)); ok {
		return returnFunc(ctx, userID, operation)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, ManagementOperation) *ManagementResult); ok {
		r0 = returnFunc(ctx, userID, operation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ManagementResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, ManagementOperation) error); ok {
		r1 = returnFunc(ctx, userID, operation)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriptionManager_GetManagementURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetManagementURL'
type MockSubscriptionManager_GetManagementURL_Call struct {
	*mock.Call
}

// GetManagementURL is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - operation ManagementOperation
func (_e *MockSubscriptionManager_Expecter) GetManagementURL(ctx interface{}, userID interface{}, operation interface{}) *MockSubscriptionManager_GetManagementURL_Call {
	return &MockSubscriptionManager_GetManagementURL_Call{Call: _e.mock.On("GetManagementURL", ctx, userID, operation)}
}

func (_c *MockSubscriptionManager_GetManagementURL_Call) Run(run func(ctx context.Context, userID uint, operation ManagementOperation)) *MockSubscriptionManager_GetManagementURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 ManagementOperation
		if args[2] != nil {
			arg2 = args[2].(ManagementOperation)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSubscriptionManager_GetManagementURL_Call) Return(managementResult *ManagementResult, err error) *MockSubscriptionManager_GetManagementURL_Call {
	_c.Call.Return(managementResult, err)
	return _c
}

func (_c *MockSubscriptionManager_GetManagementURL_Call) RunAndReturn(run func(ctx context.Context, userID uint, operation ManagementOperation) (*ManagementResult, error)) *MockSubscriptionManager_GetManagementURL_Call {
	_c.Call.Return(run)
	return _c
}
