// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package core

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCustomerPortal creates a new instance of MockCustomerPortal. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCustomerPortal(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCustomerPortal {
	mock := &MockCustomerPortal{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCustomerPortal is an autogenerated mock type for the CustomerPortal type
type MockCustomerPortal struct {
	mock.Mock
}

type MockCustomerPortal_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCustomerPortal) EXPECT() *MockCustomerPortal_Expecter {
	return &MockCustomerPortal_Expecter{mock: &_m.Mock}
}

// GetCustomerPortalMetadata provides a mock function for the type MockCustomerPortal
func (_mock *MockCustomerPortal) GetCustomerPortalMetadata(ctx context.Context, userID uint) (map[string]any, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomerPortalMetadata")
	}

	var r0 map[string]any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (map[string]any, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) map[string]any); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomerPortal_GetCustomerPortalMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCustomerPortalMetadata'
type MockCustomerPortal_GetCustomerPortalMetadata_Call struct {
	*mock.Call
}

// GetCustomerPortalMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockCustomerPortal_Expecter) GetCustomerPortalMetadata(ctx interface{}, userID interface{}) *MockCustomerPortal_GetCustomerPortalMetadata_Call {
	return &MockCustomerPortal_GetCustomerPortalMetadata_Call{Call: _e.mock.On("GetCustomerPortalMetadata", ctx, userID)}
}

func (_c *MockCustomerPortal_GetCustomerPortalMetadata_Call) Run(run func(ctx context.Context, userID uint)) *MockCustomerPortal_GetCustomerPortalMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCustomerPortal_GetCustomerPortalMetadata_Call) Return(stringToV map[string]any, err error) *MockCustomerPortal_GetCustomerPortalMetadata_Call {
	_c.Call.Return(stringToV, err)
	return _c
}

func (_c *MockCustomerPortal_GetCustomerPortalMetadata_Call) RunAndReturn(run func(ctx context.Context, userID uint) (map[string]any, error)) *MockCustomerPortal_GetCustomerPortalMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// GetCustomerPortalURL provides a mock function for the type MockCustomerPortal
func (_mock *MockCustomerPortal) GetCustomerPortalURL(ctx context.Context, userID uint, returnUrl string) (string, error) {
	ret := _mock.Called(ctx, userID, returnUrl)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomerPortalURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string) (string, error)); ok {
		return returnFunc(ctx, userID, returnUrl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string) string); ok {
		r0 = returnFunc(ctx, userID, returnUrl)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, string) error); ok {
		r1 = returnFunc(ctx, userID, returnUrl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomerPortal_GetCustomerPortalURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCustomerPortalURL'
type MockCustomerPortal_GetCustomerPortalURL_Call struct {
	*mock.Call
}

// GetCustomerPortalURL is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - returnUrl string
func (_e *MockCustomerPortal_Expecter) GetCustomerPortalURL(ctx interface{}, userID interface{}, returnUrl interface{}) *MockCustomerPortal_GetCustomerPortalURL_Call {
	return &MockCustomerPortal_GetCustomerPortalURL_Call{Call: _e.mock.On("GetCustomerPortalURL", ctx, userID, returnUrl)}
}

func (_c *MockCustomerPortal_GetCustomerPortalURL_Call) Run(run func(ctx context.Context, userID uint, returnUrl string)) *MockCustomerPortal_GetCustomerPortalURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCustomerPortal_GetCustomerPortalURL_Call) Return(s string, err error) *MockCustomerPortal_GetCustomerPortalURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockCustomerPortal_GetCustomerPortalURL_Call) RunAndReturn(run func(ctx context.Context, userID uint, returnUrl string) (string, error)) *MockCustomerPortal_GetCustomerPortalURL_Call {
	_c.Call.Return(run)
	return _c
}
