// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pricing

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-plugin-billing/core"
)

// NewMockMockablePaymentGateway creates a new instance of MockMockablePaymentGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMockablePaymentGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMockablePaymentGateway {
	mock := &MockMockablePaymentGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMockablePaymentGateway is an autogenerated mock type for the MockablePaymentGateway type
type MockMockablePaymentGateway struct {
	mock.Mock
}

type MockMockablePaymentGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMockablePaymentGateway) EXPECT() *MockMockablePaymentGateway_Expecter {
	return &MockMockablePaymentGateway_Expecter{mock: &_m.Mock}
}

// AbortCancellation provides a mock function for the type MockMockablePaymentGateway
func (_mock *MockMockablePaymentGateway) AbortCancellation(ctx context.Context, userID uint) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for AbortCancellation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMockablePaymentGateway_AbortCancellation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AbortCancellation'
type MockMockablePaymentGateway_AbortCancellation_Call struct {
	*mock.Call
}

// AbortCancellation is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockMockablePaymentGateway_Expecter) AbortCancellation(ctx interface{}, userID interface{}) *MockMockablePaymentGateway_AbortCancellation_Call {
	return &MockMockablePaymentGateway_AbortCancellation_Call{Call: _e.mock.On("AbortCancellation", ctx, userID)}
}

func (_c *MockMockablePaymentGateway_AbortCancellation_Call) Run(run func(ctx context.Context, userID uint)) *MockMockablePaymentGateway_AbortCancellation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMockablePaymentGateway_AbortCancellation_Call) Return(err error) *MockMockablePaymentGateway_AbortCancellation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMockablePaymentGateway_AbortCancellation_Call) RunAndReturn(run func(ctx context.Context, userID uint) error) *MockMockablePaymentGateway_AbortCancellation_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteCancel provides a mock function for the type MockMockablePaymentGateway
func (_mock *MockMockablePaymentGateway) ExecuteCancel(ctx context.Context, userID uint, immediate bool) (*core.CancellationResult, error) {
	ret := _mock.Called(ctx, userID, immediate)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteCancel")
	}

	var r0 *core.CancellationResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, bool) (*core.CancellationResult, error)); ok {
		return returnFunc(ctx, userID, immediate)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, bool) *core.CancellationResult); ok {
		r0 = returnFunc(ctx, userID, immediate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.CancellationResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, bool) error); ok {
		r1 = returnFunc(ctx, userID, immediate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMockablePaymentGateway_ExecuteCancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteCancel'
type MockMockablePaymentGateway_ExecuteCancel_Call struct {
	*mock.Call
}

// ExecuteCancel is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - immediate bool
func (_e *MockMockablePaymentGateway_Expecter) ExecuteCancel(ctx interface{}, userID interface{}, immediate interface{}) *MockMockablePaymentGateway_ExecuteCancel_Call {
	return &MockMockablePaymentGateway_ExecuteCancel_Call{Call: _e.mock.On("ExecuteCancel", ctx, userID, immediate)}
}

func (_c *MockMockablePaymentGateway_ExecuteCancel_Call) Run(run func(ctx context.Context, userID uint, immediate bool)) *MockMockablePaymentGateway_ExecuteCancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMockablePaymentGateway_ExecuteCancel_Call) Return(cancellationResult *core.CancellationResult, err error) *MockMockablePaymentGateway_ExecuteCancel_Call {
	_c.Call.Return(cancellationResult, err)
	return _c
}

func (_c *MockMockablePaymentGateway_ExecuteCancel_Call) RunAndReturn(run func(ctx context.Context, userID uint, immediate bool) (*core.CancellationResult, error)) *MockMockablePaymentGateway_ExecuteCancel_Call {
	_c.Call.Return(run)
	return _c
}

// ExecutePause provides a mock function for the type MockMockablePaymentGateway
func (_mock *MockMockablePaymentGateway) ExecutePause(ctx context.Context, userID uint) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ExecutePause")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMockablePaymentGateway_ExecutePause_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecutePause'
type MockMockablePaymentGateway_ExecutePause_Call struct {
	*mock.Call
}

// ExecutePause is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockMockablePaymentGateway_Expecter) ExecutePause(ctx interface{}, userID interface{}) *MockMockablePaymentGateway_ExecutePause_Call {
	return &MockMockablePaymentGateway_ExecutePause_Call{Call: _e.mock.On("ExecutePause", ctx, userID)}
}

func (_c *MockMockablePaymentGateway_ExecutePause_Call) Run(run func(ctx context.Context, userID uint)) *MockMockablePaymentGateway_ExecutePause_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMockablePaymentGateway_ExecutePause_Call) Return(err error) *MockMockablePaymentGateway_ExecutePause_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMockablePaymentGateway_ExecutePause_Call) RunAndReturn(run func(ctx context.Context, userID uint) error) *MockMockablePaymentGateway_ExecutePause_Call {
	_c.Call.Return(run)
	return _c
}

// ExecutePlanChange provides a mock function for the type MockMockablePaymentGateway
func (_mock *MockMockablePaymentGateway) ExecutePlanChange(ctx context.Context, userID uint, newPeriodID uint) (*core.PlanChangeResult, error) {
	ret := _mock.Called(ctx, userID, newPeriodID)

	if len(ret) == 0 {
		panic("no return value specified for ExecutePlanChange")
	}

	var r0 *core.PlanChangeResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) (*core.PlanChangeResult, error)); ok {
		return returnFunc(ctx, userID, newPeriodID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) *core.PlanChangeResult); ok {
		r0 = returnFunc(ctx, userID, newPeriodID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.PlanChangeResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = returnFunc(ctx, userID, newPeriodID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMockablePaymentGateway_ExecutePlanChange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecutePlanChange'
type MockMockablePaymentGateway_ExecutePlanChange_Call struct {
	*mock.Call
}

// ExecutePlanChange is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - newPeriodID uint
func (_e *MockMockablePaymentGateway_Expecter) ExecutePlanChange(ctx interface{}, userID interface{}, newPeriodID interface{}) *MockMockablePaymentGateway_ExecutePlanChange_Call {
	return &MockMockablePaymentGateway_ExecutePlanChange_Call{Call: _e.mock.On("ExecutePlanChange", ctx, userID, newPeriodID)}
}

func (_c *MockMockablePaymentGateway_ExecutePlanChange_Call) Run(run func(ctx context.Context, userID uint, newPeriodID uint)) *MockMockablePaymentGateway_ExecutePlanChange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMockablePaymentGateway_ExecutePlanChange_Call) Return(planChangeResult *core.PlanChangeResult, err error) *MockMockablePaymentGateway_ExecutePlanChange_Call {
	_c.Call.Return(planChangeResult, err)
	return _c
}

func (_c *MockMockablePaymentGateway_ExecutePlanChange_Call) RunAndReturn(run func(ctx context.Context, userID uint, newPeriodID uint) (*core.PlanChangeResult, error)) *MockMockablePaymentGateway_ExecutePlanChange_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteResume provides a mock function for the type MockMockablePaymentGateway
func (_mock *MockMockablePaymentGateway) ExecuteResume(ctx context.Context, userID uint) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteResume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMockablePaymentGateway_ExecuteResume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteResume'
type MockMockablePaymentGateway_ExecuteResume_Call struct {
	*mock.Call
}

// ExecuteResume is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockMockablePaymentGateway_Expecter) ExecuteResume(ctx interface{}, userID interface{}) *MockMockablePaymentGateway_ExecuteResume_Call {
	return &MockMockablePaymentGateway_ExecuteResume_Call{Call: _e.mock.On("ExecuteResume", ctx, userID)}
}

func (_c *MockMockablePaymentGateway_ExecuteResume_Call) Run(run func(ctx context.Context, userID uint)) *MockMockablePaymentGateway_ExecuteResume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMockablePaymentGateway_ExecuteResume_Call) Return(err error) *MockMockablePaymentGateway_ExecuteResume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMockablePaymentGateway_ExecuteResume_Call) RunAndReturn(run func(ctx context.Context, userID uint) error) *MockMockablePaymentGateway_ExecuteResume_Call {
	_c.Call.Return(run)
	return _c
}

// ExtractEventID provides a mock function for the type MockMockablePaymentGateway
func (_mock *MockMockablePaymentGateway) ExtractEventID(ctx context.Context, payload []byte) (string, error) {
	ret := _mock.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for ExtractEventID")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) (string, error)); ok {
		return returnFunc(ctx, payload)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) string); ok {
		r0 = returnFunc(ctx, payload)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMockablePaymentGateway_ExtractEventID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractEventID'
type MockMockablePaymentGateway_ExtractEventID_Call struct {
	*mock.Call
}

// ExtractEventID is a helper method to define mock.On call
//   - ctx context.Context
//   - payload []byte
func (_e *MockMockablePaymentGateway_Expecter) ExtractEventID(ctx interface{}, payload interface{}) *MockMockablePaymentGateway_ExtractEventID_Call {
	return &MockMockablePaymentGateway_ExtractEventID_Call{Call: _e.mock.On("ExtractEventID", ctx, payload)}
}

func (_c *MockMockablePaymentGateway_ExtractEventID_Call) Run(run func(ctx context.Context, payload []byte)) *MockMockablePaymentGateway_ExtractEventID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMockablePaymentGateway_ExtractEventID_Call) Return(s string, err error) *MockMockablePaymentGateway_ExtractEventID_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockMockablePaymentGateway_ExtractEventID_Call) RunAndReturn(run func(ctx context.Context, payload []byte) (string, error)) *MockMockablePaymentGateway_ExtractEventID_Call {
	_c.Call.Return(run)
	return _c
}

// ExtractEventType provides a mock function for the type MockMockablePaymentGateway
func (_mock *MockMockablePaymentGateway) ExtractEventType(ctx context.Context, payload []byte) (string, error) {
	ret := _mock.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for ExtractEventType")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) (string, error)); ok {
		return returnFunc(ctx, payload)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) string); ok {
		r0 = returnFunc(ctx, payload)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMockablePaymentGateway_ExtractEventType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractEventType'
type MockMockablePaymentGateway_ExtractEventType_Call struct {
	*mock.Call
}

// ExtractEventType is a helper method to define mock.On call
//   - ctx context.Context
//   - payload []byte
func (_e *MockMockablePaymentGateway_Expecter) ExtractEventType(ctx interface{}, payload interface{}) *MockMockablePaymentGateway_ExtractEventType_Call {
	return &MockMockablePaymentGateway_ExtractEventType_Call{Call: _e.mock.On("ExtractEventType", ctx, payload)}
}

func (_c *MockMockablePaymentGateway_ExtractEventType_Call) Run(run func(ctx context.Context, payload []byte)) *MockMockablePaymentGateway_ExtractEventType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMockablePaymentGateway_ExtractEventType_Call) Return(s string, err error) *MockMockablePaymentGateway_ExtractEventType_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockMockablePaymentGateway_ExtractEventType_Call) RunAndReturn(run func(ctx context.Context, payload []byte) (string, error)) *MockMockablePaymentGateway_ExtractEventType_Call {
	_c.Call.Return(run)
	return _c
}

// GetCheckoutUI provides a mock function for the type MockMockablePaymentGateway
func (_mock *MockMockablePaymentGateway) GetCheckoutUI(ctx context.Context, userID uint, planID uint, periodID uint) (*core.CheckoutUIResponse, error) {
	ret := _mock.Called(ctx, userID, planID, periodID)

	if len(ret) == 0 {
		panic("no return value specified for GetCheckoutUI")
	}

	var r0 *core.CheckoutUIResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, uint) (*core.CheckoutUIResponse, error)); ok {
		return returnFunc(ctx, userID, planID, periodID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, uint) *core.CheckoutUIResponse); ok {
		r0 = returnFunc(ctx, userID, planID, periodID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.CheckoutUIResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, uint, uint) error); ok {
		r1 = returnFunc(ctx, userID, planID, periodID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMockablePaymentGateway_GetCheckoutUI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCheckoutUI'
type MockMockablePaymentGateway_GetCheckoutUI_Call struct {
	*mock.Call
}

// GetCheckoutUI is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - planID uint
//   - periodID uint
func (_e *MockMockablePaymentGateway_Expecter) GetCheckoutUI(ctx interface{}, userID interface{}, planID interface{}, periodID interface{}) *MockMockablePaymentGateway_GetCheckoutUI_Call {
	return &MockMockablePaymentGateway_GetCheckoutUI_Call{Call: _e.mock.On("GetCheckoutUI", ctx, userID, planID, periodID)}
}

func (_c *MockMockablePaymentGateway_GetCheckoutUI_Call) Run(run func(ctx context.Context, userID uint, planID uint, periodID uint)) *MockMockablePaymentGateway_GetCheckoutUI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		var arg3 uint
		if args[3] != nil {
			arg3 = args[3].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMockablePaymentGateway_GetCheckoutUI_Call) Return(checkoutUIResponse *core.CheckoutUIResponse, err error) *MockMockablePaymentGateway_GetCheckoutUI_Call {
	_c.Call.Return(checkoutUIResponse, err)
	return _c
}

func (_c *MockMockablePaymentGateway_GetCheckoutUI_Call) RunAndReturn(run func(ctx context.Context, userID uint, planID uint, periodID uint) (*core.CheckoutUIResponse, error)) *MockMockablePaymentGateway_GetCheckoutUI_Call {
	_c.Call.Return(run)
	return _c
}

// GetCustomerPortalMetadata provides a mock function for the type MockMockablePaymentGateway
func (_mock *MockMockablePaymentGateway) GetCustomerPortalMetadata(ctx context.Context, userID uint) (map[string]any, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomerPortalMetadata")
	}

	var r0 map[string]any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (map[string]any, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) map[string]any); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMockablePaymentGateway_GetCustomerPortalMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCustomerPortalMetadata'
type MockMockablePaymentGateway_GetCustomerPortalMetadata_Call struct {
	*mock.Call
}

// GetCustomerPortalMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockMockablePaymentGateway_Expecter) GetCustomerPortalMetadata(ctx interface{}, userID interface{}) *MockMockablePaymentGateway_GetCustomerPortalMetadata_Call {
	return &MockMockablePaymentGateway_GetCustomerPortalMetadata_Call{Call: _e.mock.On("GetCustomerPortalMetadata", ctx, userID)}
}

func (_c *MockMockablePaymentGateway_GetCustomerPortalMetadata_Call) Run(run func(ctx context.Context, userID uint)) *MockMockablePaymentGateway_GetCustomerPortalMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMockablePaymentGateway_GetCustomerPortalMetadata_Call) Return(stringToV map[string]any, err error) *MockMockablePaymentGateway_GetCustomerPortalMetadata_Call {
	_c.Call.Return(stringToV, err)
	return _c
}

func (_c *MockMockablePaymentGateway_GetCustomerPortalMetadata_Call) RunAndReturn(run func(ctx context.Context, userID uint) (map[string]any, error)) *MockMockablePaymentGateway_GetCustomerPortalMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// GetCustomerPortalURL provides a mock function for the type MockMockablePaymentGateway
func (_mock *MockMockablePaymentGateway) GetCustomerPortalURL(ctx context.Context, userID uint, returnUrl string) (string, error) {
	ret := _mock.Called(ctx, userID, returnUrl)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomerPortalURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string) (string, error)); ok {
		return returnFunc(ctx, userID, returnUrl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string) string); ok {
		r0 = returnFunc(ctx, userID, returnUrl)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, string) error); ok {
		r1 = returnFunc(ctx, userID, returnUrl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMockablePaymentGateway_GetCustomerPortalURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCustomerPortalURL'
type MockMockablePaymentGateway_GetCustomerPortalURL_Call struct {
	*mock.Call
}

// GetCustomerPortalURL is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - returnUrl string
func (_e *MockMockablePaymentGateway_Expecter) GetCustomerPortalURL(ctx interface{}, userID interface{}, returnUrl interface{}) *MockMockablePaymentGateway_GetCustomerPortalURL_Call {
	return &MockMockablePaymentGateway_GetCustomerPortalURL_Call{Call: _e.mock.On("GetCustomerPortalURL", ctx, userID, returnUrl)}
}

func (_c *MockMockablePaymentGateway_GetCustomerPortalURL_Call) Run(run func(ctx context.Context, userID uint, returnUrl string)) *MockMockablePaymentGateway_GetCustomerPortalURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMockablePaymentGateway_GetCustomerPortalURL_Call) Return(s string, err error) *MockMockablePaymentGateway_GetCustomerPortalURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockMockablePaymentGateway_GetCustomerPortalURL_Call) RunAndReturn(run func(ctx context.Context, userID uint, returnUrl string) (string, error)) *MockMockablePaymentGateway_GetCustomerPortalURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetDescription provides a mock function for the type MockMockablePaymentGateway
func (_mock *MockMockablePaymentGateway) GetDescription(ctx context.Context) string {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDescription")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockMockablePaymentGateway_GetDescription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDescription'
type MockMockablePaymentGateway_GetDescription_Call struct {
	*mock.Call
}

// GetDescription is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMockablePaymentGateway_Expecter) GetDescription(ctx interface{}) *MockMockablePaymentGateway_GetDescription_Call {
	return &MockMockablePaymentGateway_GetDescription_Call{Call: _e.mock.On("GetDescription", ctx)}
}

func (_c *MockMockablePaymentGateway_GetDescription_Call) Run(run func(ctx context.Context)) *MockMockablePaymentGateway_GetDescription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMockablePaymentGateway_GetDescription_Call) Return(s string) *MockMockablePaymentGateway_GetDescription_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockMockablePaymentGateway_GetDescription_Call) RunAndReturn(run func(ctx context.Context) string) *MockMockablePaymentGateway_GetDescription_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogo provides a mock function for the type MockMockablePaymentGateway
func (_mock *MockMockablePaymentGateway) GetLogo(ctx context.Context) ([]byte, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLogo")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]byte, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []byte); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMockablePaymentGateway_GetLogo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogo'
type MockMockablePaymentGateway_GetLogo_Call struct {
	*mock.Call
}

// GetLogo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMockablePaymentGateway_Expecter) GetLogo(ctx interface{}) *MockMockablePaymentGateway_GetLogo_Call {
	return &MockMockablePaymentGateway_GetLogo_Call{Call: _e.mock.On("GetLogo", ctx)}
}

func (_c *MockMockablePaymentGateway_GetLogo_Call) Run(run func(ctx context.Context)) *MockMockablePaymentGateway_GetLogo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMockablePaymentGateway_GetLogo_Call) Return(bytes []byte, err error) *MockMockablePaymentGateway_GetLogo_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockMockablePaymentGateway_GetLogo_Call) RunAndReturn(run func(ctx context.Context) ([]byte, error)) *MockMockablePaymentGateway_GetLogo_Call {
	_c.Call.Return(run)
	return _c
}

// GetManagementInfo provides a mock function for the type MockMockablePaymentGateway
func (_mock *MockMockablePaymentGateway) GetManagementInfo(ctx context.Context, userID uint) (*core.ManagementCapabilities, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetManagementInfo")
	}

	var r0 *core.ManagementCapabilities
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*core.ManagementCapabilities, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *core.ManagementCapabilities); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.ManagementCapabilities)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMockablePaymentGateway_GetManagementInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetManagementInfo'
type MockMockablePaymentGateway_GetManagementInfo_Call struct {
	*mock.Call
}

// GetManagementInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockMockablePaymentGateway_Expecter) GetManagementInfo(ctx interface{}, userID interface{}) *MockMockablePaymentGateway_GetManagementInfo_Call {
	return &MockMockablePaymentGateway_GetManagementInfo_Call{Call: _e.mock.On("GetManagementInfo", ctx, userID)}
}

func (_c *MockMockablePaymentGateway_GetManagementInfo_Call) Run(run func(ctx context.Context, userID uint)) *MockMockablePaymentGateway_GetManagementInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMockablePaymentGateway_GetManagementInfo_Call) Return(managementCapabilities *core.ManagementCapabilities, err error) *MockMockablePaymentGateway_GetManagementInfo_Call {
	_c.Call.Return(managementCapabilities, err)
	return _c
}

func (_c *MockMockablePaymentGateway_GetManagementInfo_Call) RunAndReturn(run func(ctx context.Context, userID uint) (*core.ManagementCapabilities, error)) *MockMockablePaymentGateway_GetManagementInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetManagementURL provides a mock function for the type MockMockablePaymentGateway
func (_mock *MockMockablePaymentGateway) GetManagementURL(ctx context.Context, userID uint, operation core.ManagementOperation) (*core.ManagementResult, error) {
	ret := _mock.Called(ctx, userID, operation)

	if len(ret) == 0 {
		panic("no return value specified for GetManagementURL")
	}

	var r0 *core.ManagementResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, core.ManagementOperation) (*core.ManagementResult, error)); ok {
		return returnFunc(ctx, userID, operation)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, core.ManagementOperation) *core.ManagementResult); ok {
		r0 = returnFunc(ctx, userID, operation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.ManagementResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, core.ManagementOperation) error); ok {
		r1 = returnFunc(ctx, userID, operation)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMockablePaymentGateway_GetManagementURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetManagementURL'
type MockMockablePaymentGateway_GetManagementURL_Call struct {
	*mock.Call
}

// GetManagementURL is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - operation core.ManagementOperation
func (_e *MockMockablePaymentGateway_Expecter) GetManagementURL(ctx interface{}, userID interface{}, operation interface{}) *MockMockablePaymentGateway_GetManagementURL_Call {
	return &MockMockablePaymentGateway_GetManagementURL_Call{Call: _e.mock.On("GetManagementURL", ctx, userID, operation)}
}

func (_c *MockMockablePaymentGateway_GetManagementURL_Call) Run(run func(ctx context.Context, userID uint, operation core.ManagementOperation)) *MockMockablePaymentGateway_GetManagementURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 core.ManagementOperation
		if args[2] != nil {
			arg2 = args[2].(core.ManagementOperation)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMockablePaymentGateway_GetManagementURL_Call) Return(managementResult *core.ManagementResult, err error) *MockMockablePaymentGateway_GetManagementURL_Call {
	_c.Call.Return(managementResult, err)
	return _c
}

func (_c *MockMockablePaymentGateway_GetManagementURL_Call) RunAndReturn(run func(ctx context.Context, userID uint, operation core.ManagementOperation) (*core.ManagementResult, error)) *MockMockablePaymentGateway_GetManagementURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function for the type MockMockablePaymentGateway
func (_mock *MockMockablePaymentGateway) GetName(ctx context.Context) string {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockMockablePaymentGateway_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type MockMockablePaymentGateway_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMockablePaymentGateway_Expecter) GetName(ctx interface{}) *MockMockablePaymentGateway_GetName_Call {
	return &MockMockablePaymentGateway_GetName_Call{Call: _e.mock.On("GetName", ctx)}
}

func (_c *MockMockablePaymentGateway_GetName_Call) Run(run func(ctx context.Context)) *MockMockablePaymentGateway_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMockablePaymentGateway_GetName_Call) Return(s string) *MockMockablePaymentGateway_GetName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockMockablePaymentGateway_GetName_Call) RunAndReturn(run func(ctx context.Context) string) *MockMockablePaymentGateway_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionStatus provides a mock function for the type MockMockablePaymentGateway
func (_mock *MockMockablePaymentGateway) GetSessionStatus(ctx context.Context, sessionID string) (*core.SessionStatus, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionStatus")
	}

	var r0 *core.SessionStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*core.SessionStatus, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *core.SessionStatus); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.SessionStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMockablePaymentGateway_GetSessionStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionStatus'
type MockMockablePaymentGateway_GetSessionStatus_Call struct {
	*mock.Call
}

// GetSessionStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockMockablePaymentGateway_Expecter) GetSessionStatus(ctx interface{}, sessionID interface{}) *MockMockablePaymentGateway_GetSessionStatus_Call {
	return &MockMockablePaymentGateway_GetSessionStatus_Call{Call: _e.mock.On("GetSessionStatus", ctx, sessionID)}
}

func (_c *MockMockablePaymentGateway_GetSessionStatus_Call) Run(run func(ctx context.Context, sessionID string)) *MockMockablePaymentGateway_GetSessionStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMockablePaymentGateway_GetSessionStatus_Call) Return(sessionStatus *core.SessionStatus, err error) *MockMockablePaymentGateway_GetSessionStatus_Call {
	_c.Call.Return(sessionStatus, err)
	return _c
}

func (_c *MockMockablePaymentGateway_GetSessionStatus_Call) RunAndReturn(run func(ctx context.Context, sessionID string) (*core.SessionStatus, error)) *MockMockablePaymentGateway_GetSessionStatus_Call {
	_c.Call.Return(run)
	return _c
}

// HandleWebhook provides a mock function for the type MockMockablePaymentGateway
func (_mock *MockMockablePaymentGateway) HandleWebhook(ctx context.Context, payload []byte) error {
	ret := _mock.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for HandleWebhook")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = returnFunc(ctx, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMockablePaymentGateway_HandleWebhook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleWebhook'
type MockMockablePaymentGateway_HandleWebhook_Call struct {
	*mock.Call
}

// HandleWebhook is a helper method to define mock.On call
//   - ctx context.Context
//   - payload []byte
func (_e *MockMockablePaymentGateway_Expecter) HandleWebhook(ctx interface{}, payload interface{}) *MockMockablePaymentGateway_HandleWebhook_Call {
	return &MockMockablePaymentGateway_HandleWebhook_Call{Call: _e.mock.On("HandleWebhook", ctx, payload)}
}

func (_c *MockMockablePaymentGateway_HandleWebhook_Call) Run(run func(ctx context.Context, payload []byte)) *MockMockablePaymentGateway_HandleWebhook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMockablePaymentGateway_HandleWebhook_Call) Return(err error) *MockMockablePaymentGateway_HandleWebhook_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMockablePaymentGateway_HandleWebhook_Call) RunAndReturn(run func(ctx context.Context, payload []byte) error) *MockMockablePaymentGateway_HandleWebhook_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockMockablePaymentGateway
func (_mock *MockMockablePaymentGateway) ID(ctx context.Context) string {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockMockablePaymentGateway_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockMockablePaymentGateway_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMockablePaymentGateway_Expecter) ID(ctx interface{}) *MockMockablePaymentGateway_ID_Call {
	return &MockMockablePaymentGateway_ID_Call{Call: _e.mock.On("ID", ctx)}
}

func (_c *MockMockablePaymentGateway_ID_Call) Run(run func(ctx context.Context)) *MockMockablePaymentGateway_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMockablePaymentGateway_ID_Call) Return(s string) *MockMockablePaymentGateway_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockMockablePaymentGateway_ID_Call) RunAndReturn(run func(ctx context.Context) string) *MockMockablePaymentGateway_ID_Call {
	_c.Call.Return(run)
	return _c
}

// ReconcileCancellation provides a mock function for the type MockMockablePaymentGateway
func (_mock *MockMockablePaymentGateway) ReconcileCancellation(ctx context.Context, userID uint) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ReconcileCancellation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMockablePaymentGateway_ReconcileCancellation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReconcileCancellation'
type MockMockablePaymentGateway_ReconcileCancellation_Call struct {
	*mock.Call
}

// ReconcileCancellation is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockMockablePaymentGateway_Expecter) ReconcileCancellation(ctx interface{}, userID interface{}) *MockMockablePaymentGateway_ReconcileCancellation_Call {
	return &MockMockablePaymentGateway_ReconcileCancellation_Call{Call: _e.mock.On("ReconcileCancellation", ctx, userID)}
}

func (_c *MockMockablePaymentGateway_ReconcileCancellation_Call) Run(run func(ctx context.Context, userID uint)) *MockMockablePaymentGateway_ReconcileCancellation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMockablePaymentGateway_ReconcileCancellation_Call) Return(err error) *MockMockablePaymentGateway_ReconcileCancellation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMockablePaymentGateway_ReconcileCancellation_Call) RunAndReturn(run func(ctx context.Context, userID uint) error) *MockMockablePaymentGateway_ReconcileCancellation_Call {
	_c.Call.Return(run)
	return _c
}

// RequiredPricingFields provides a mock function for the type MockMockablePaymentGateway
func (_mock *MockMockablePaymentGateway) RequiredPricingFields() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RequiredPricingFields")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockMockablePaymentGateway_RequiredPricingFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequiredPricingFields'
type MockMockablePaymentGateway_RequiredPricingFields_Call struct {
	*mock.Call
}

// RequiredPricingFields is a helper method to define mock.On call
func (_e *MockMockablePaymentGateway_Expecter) RequiredPricingFields() *MockMockablePaymentGateway_RequiredPricingFields_Call {
	return &MockMockablePaymentGateway_RequiredPricingFields_Call{Call: _e.mock.On("RequiredPricingFields")}
}

func (_c *MockMockablePaymentGateway_RequiredPricingFields_Call) Run(run func()) *MockMockablePaymentGateway_RequiredPricingFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMockablePaymentGateway_RequiredPricingFields_Call) Return(strings []string) *MockMockablePaymentGateway_RequiredPricingFields_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockMockablePaymentGateway_RequiredPricingFields_Call) RunAndReturn(run func() []string) *MockMockablePaymentGateway_RequiredPricingFields_Call {
	_c.Call.Return(run)
	return _c
}

// SignatureHeader provides a mock function for the type MockMockablePaymentGateway
func (_mock *MockMockablePaymentGateway) SignatureHeader(ctx context.Context) string {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SignatureHeader")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockMockablePaymentGateway_SignatureHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignatureHeader'
type MockMockablePaymentGateway_SignatureHeader_Call struct {
	*mock.Call
}

// SignatureHeader is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMockablePaymentGateway_Expecter) SignatureHeader(ctx interface{}) *MockMockablePaymentGateway_SignatureHeader_Call {
	return &MockMockablePaymentGateway_SignatureHeader_Call{Call: _e.mock.On("SignatureHeader", ctx)}
}

func (_c *MockMockablePaymentGateway_SignatureHeader_Call) Run(run func(ctx context.Context)) *MockMockablePaymentGateway_SignatureHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMockablePaymentGateway_SignatureHeader_Call) Return(s string) *MockMockablePaymentGateway_SignatureHeader_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockMockablePaymentGateway_SignatureHeader_Call) RunAndReturn(run func(ctx context.Context) string) *MockMockablePaymentGateway_SignatureHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SupportsPlanDeletion provides a mock function for the type MockMockablePaymentGateway
func (_mock *MockMockablePaymentGateway) SupportsPlanDeletion() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportsPlanDeletion")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockMockablePaymentGateway_SupportsPlanDeletion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportsPlanDeletion'
type MockMockablePaymentGateway_SupportsPlanDeletion_Call struct {
	*mock.Call
}

// SupportsPlanDeletion is a helper method to define mock.On call
func (_e *MockMockablePaymentGateway_Expecter) SupportsPlanDeletion() *MockMockablePaymentGateway_SupportsPlanDeletion_Call {
	return &MockMockablePaymentGateway_SupportsPlanDeletion_Call{Call: _e.mock.On("SupportsPlanDeletion")}
}

func (_c *MockMockablePaymentGateway_SupportsPlanDeletion_Call) Run(run func()) *MockMockablePaymentGateway_SupportsPlanDeletion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMockablePaymentGateway_SupportsPlanDeletion_Call) Return(b bool) *MockMockablePaymentGateway_SupportsPlanDeletion_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockMockablePaymentGateway_SupportsPlanDeletion_Call) RunAndReturn(run func() bool) *MockMockablePaymentGateway_SupportsPlanDeletion_Call {
	_c.Call.Return(run)
	return _c
}

// SupportsPriceUpdates provides a mock function for the type MockMockablePaymentGateway
func (_mock *MockMockablePaymentGateway) SupportsPriceUpdates() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportsPriceUpdates")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockMockablePaymentGateway_SupportsPriceUpdates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportsPriceUpdates'
type MockMockablePaymentGateway_SupportsPriceUpdates_Call struct {
	*mock.Call
}

// SupportsPriceUpdates is a helper method to define mock.On call
func (_e *MockMockablePaymentGateway_Expecter) SupportsPriceUpdates() *MockMockablePaymentGateway_SupportsPriceUpdates_Call {
	return &MockMockablePaymentGateway_SupportsPriceUpdates_Call{Call: _e.mock.On("SupportsPriceUpdates")}
}

func (_c *MockMockablePaymentGateway_SupportsPriceUpdates_Call) Run(run func()) *MockMockablePaymentGateway_SupportsPriceUpdates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMockablePaymentGateway_SupportsPriceUpdates_Call) Return(b bool) *MockMockablePaymentGateway_SupportsPriceUpdates_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockMockablePaymentGateway_SupportsPriceUpdates_Call) RunAndReturn(run func() bool) *MockMockablePaymentGateway_SupportsPriceUpdates_Call {
	_c.Call.Return(run)
	return _c
}

// SupportsProductSync provides a mock function for the type MockMockablePaymentGateway
func (_mock *MockMockablePaymentGateway) SupportsProductSync() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportsProductSync")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockMockablePaymentGateway_SupportsProductSync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportsProductSync'
type MockMockablePaymentGateway_SupportsProductSync_Call struct {
	*mock.Call
}

// SupportsProductSync is a helper method to define mock.On call
func (_e *MockMockablePaymentGateway_Expecter) SupportsProductSync() *MockMockablePaymentGateway_SupportsProductSync_Call {
	return &MockMockablePaymentGateway_SupportsProductSync_Call{Call: _e.mock.On("SupportsProductSync")}
}

func (_c *MockMockablePaymentGateway_SupportsProductSync_Call) Run(run func()) *MockMockablePaymentGateway_SupportsProductSync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMockablePaymentGateway_SupportsProductSync_Call) Return(b bool) *MockMockablePaymentGateway_SupportsProductSync_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockMockablePaymentGateway_SupportsProductSync_Call) RunAndReturn(run func() bool) *MockMockablePaymentGateway_SupportsProductSync_Call {
	_c.Call.Return(run)
	return _c
}

// SyncPlan provides a mock function for the type MockMockablePaymentGateway
func (_mock *MockMockablePaymentGateway) SyncPlan(ctx context.Context, plan *core.PricingPlanInfo) (*core.SyncResult, error) {
	ret := _mock.Called(ctx, plan)

	if len(ret) == 0 {
		panic("no return value specified for SyncPlan")
	}

	var r0 *core.SyncResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.PricingPlanInfo) (*core.SyncResult, error)); ok {
		return returnFunc(ctx, plan)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.PricingPlanInfo) *core.SyncResult); ok {
		r0 = returnFunc(ctx, plan)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.SyncResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.PricingPlanInfo) error); ok {
		r1 = returnFunc(ctx, plan)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMockablePaymentGateway_SyncPlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncPlan'
type MockMockablePaymentGateway_SyncPlan_Call struct {
	*mock.Call
}

// SyncPlan is a helper method to define mock.On call
//   - ctx context.Context
//   - plan *core.PricingPlanInfo
func (_e *MockMockablePaymentGateway_Expecter) SyncPlan(ctx interface{}, plan interface{}) *MockMockablePaymentGateway_SyncPlan_Call {
	return &MockMockablePaymentGateway_SyncPlan_Call{Call: _e.mock.On("SyncPlan", ctx, plan)}
}

func (_c *MockMockablePaymentGateway_SyncPlan_Call) Run(run func(ctx context.Context, plan *core.PricingPlanInfo)) *MockMockablePaymentGateway_SyncPlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.PricingPlanInfo
		if args[1] != nil {
			arg1 = args[1].(*core.PricingPlanInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMockablePaymentGateway_SyncPlan_Call) Return(syncResult *core.SyncResult, err error) *MockMockablePaymentGateway_SyncPlan_Call {
	_c.Call.Return(syncResult, err)
	return _c
}

func (_c *MockMockablePaymentGateway_SyncPlan_Call) RunAndReturn(run func(ctx context.Context, plan *core.PricingPlanInfo) (*core.SyncResult, error)) *MockMockablePaymentGateway_SyncPlan_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateWebhook provides a mock function for the type MockMockablePaymentGateway
func (_mock *MockMockablePaymentGateway) ValidateWebhook(ctx context.Context, signature string, payload []byte) error {
	ret := _mock.Called(ctx, signature, payload)

	if len(ret) == 0 {
		panic("no return value specified for ValidateWebhook")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = returnFunc(ctx, signature, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMockablePaymentGateway_ValidateWebhook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateWebhook'
type MockMockablePaymentGateway_ValidateWebhook_Call struct {
	*mock.Call
}

// ValidateWebhook is a helper method to define mock.On call
//   - ctx context.Context
//   - signature string
//   - payload []byte
func (_e *MockMockablePaymentGateway_Expecter) ValidateWebhook(ctx interface{}, signature interface{}, payload interface{}) *MockMockablePaymentGateway_ValidateWebhook_Call {
	return &MockMockablePaymentGateway_ValidateWebhook_Call{Call: _e.mock.On("ValidateWebhook", ctx, signature, payload)}
}

func (_c *MockMockablePaymentGateway_ValidateWebhook_Call) Run(run func(ctx context.Context, signature string, payload []byte)) *MockMockablePaymentGateway_ValidateWebhook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMockablePaymentGateway_ValidateWebhook_Call) Return(err error) *MockMockablePaymentGateway_ValidateWebhook_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMockablePaymentGateway_ValidateWebhook_Call) RunAndReturn(run func(ctx context.Context, signature string, payload []byte) error) *MockMockablePaymentGateway_ValidateWebhook_Call {
	_c.Call.Return(run)
	return _c
}
