// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ledger

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-plugin-billing/pkg/ledger"
)

// NewMockCreditRepository creates a new instance of MockCreditRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreditRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreditRepository {
	mock := &MockCreditRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreditRepository is an autogenerated mock type for the CreditRepository type
type MockCreditRepository struct {
	mock.Mock
}

type MockCreditRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreditRepository) EXPECT() *MockCreditRepository_Expecter {
	return &MockCreditRepository_Expecter{mock: &_m.Mock}
}

// CreateCredit provides a mock function for the type MockCreditRepository
func (_mock *MockCreditRepository) CreateCredit(ctx context.Context, credit *ledger.Credit) error {
	ret := _mock.Called(ctx, credit)

	if len(ret) == 0 {
		panic("no return value specified for CreateCredit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ledger.Credit) error); ok {
		r0 = returnFunc(ctx, credit)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCreditRepository_CreateCredit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCredit'
type MockCreditRepository_CreateCredit_Call struct {
	*mock.Call
}

// CreateCredit is a helper method to define mock.On call
//   - ctx context.Context
//   - credit *ledger.Credit
func (_e *MockCreditRepository_Expecter) CreateCredit(ctx interface{}, credit interface{}) *MockCreditRepository_CreateCredit_Call {
	return &MockCreditRepository_CreateCredit_Call{Call: _e.mock.On("CreateCredit", ctx, credit)}
}

func (_c *MockCreditRepository_CreateCredit_Call) Run(run func(ctx context.Context, credit *ledger.Credit)) *MockCreditRepository_CreateCredit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ledger.Credit
		if args[1] != nil {
			arg1 = args[1].(*ledger.Credit)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreditRepository_CreateCredit_Call) Return(err error) *MockCreditRepository_CreateCredit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCreditRepository_CreateCredit_Call) RunAndReturn(run func(ctx context.Context, credit *ledger.Credit) error) *MockCreditRepository_CreateCredit_Call {
	_c.Call.Return(run)
	return _c
}

// GetCredit provides a mock function for the type MockCreditRepository
func (_mock *MockCreditRepository) GetCredit(ctx context.Context, id uuid.UUID) (*ledger.Credit, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCredit")
	}

	var r0 *ledger.Credit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*ledger.Credit, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *ledger.Credit); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ledger.Credit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreditRepository_GetCredit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCredit'
type MockCreditRepository_GetCredit_Call struct {
	*mock.Call
}

// GetCredit is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCreditRepository_Expecter) GetCredit(ctx interface{}, id interface{}) *MockCreditRepository_GetCredit_Call {
	return &MockCreditRepository_GetCredit_Call{Call: _e.mock.On("GetCredit", ctx, id)}
}

func (_c *MockCreditRepository_GetCredit_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCreditRepository_GetCredit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreditRepository_GetCredit_Call) Return(credit *ledger.Credit, err error) *MockCreditRepository_GetCredit_Call {
	_c.Call.Return(credit, err)
	return _c
}

func (_c *MockCreditRepository_GetCredit_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*ledger.Credit, error)) *MockCreditRepository_GetCredit_Call {
	_c.Call.Return(run)
	return _c
}

// GetCreditsByReference provides a mock function for the type MockCreditRepository
func (_mock *MockCreditRepository) GetCreditsByReference(ctx context.Context, referenceID string, referenceType string) ([]ledger.Credit, error) {
	ret := _mock.Called(ctx, referenceID, referenceType)

	if len(ret) == 0 {
		panic("no return value specified for GetCreditsByReference")
	}

	var r0 []ledger.Credit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]ledger.Credit, error)); ok {
		return returnFunc(ctx, referenceID, referenceType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []ledger.Credit); ok {
		r0 = returnFunc(ctx, referenceID, referenceType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ledger.Credit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, referenceID, referenceType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreditRepository_GetCreditsByReference_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCreditsByReference'
type MockCreditRepository_GetCreditsByReference_Call struct {
	*mock.Call
}

// GetCreditsByReference is a helper method to define mock.On call
//   - ctx context.Context
//   - referenceID string
//   - referenceType string
func (_e *MockCreditRepository_Expecter) GetCreditsByReference(ctx interface{}, referenceID interface{}, referenceType interface{}) *MockCreditRepository_GetCreditsByReference_Call {
	return &MockCreditRepository_GetCreditsByReference_Call{Call: _e.mock.On("GetCreditsByReference", ctx, referenceID, referenceType)}
}

func (_c *MockCreditRepository_GetCreditsByReference_Call) Run(run func(ctx context.Context, referenceID string, referenceType string)) *MockCreditRepository_GetCreditsByReference_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCreditRepository_GetCreditsByReference_Call) Return(credits []ledger.Credit, err error) *MockCreditRepository_GetCreditsByReference_Call {
	_c.Call.Return(credits, err)
	return _c
}

func (_c *MockCreditRepository_GetCreditsByReference_Call) RunAndReturn(run func(ctx context.Context, referenceID string, referenceType string) ([]ledger.Credit, error)) *MockCreditRepository_GetCreditsByReference_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeletedCredits provides a mock function for the type MockCreditRepository
func (_mock *MockCreditRepository) GetDeletedCredits(ctx context.Context, userID uint64) ([]ledger.Credit, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetDeletedCredits")
	}

	var r0 []ledger.Credit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) ([]ledger.Credit, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) []ledger.Credit); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ledger.Credit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreditRepository_GetDeletedCredits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeletedCredits'
type MockCreditRepository_GetDeletedCredits_Call struct {
	*mock.Call
}

// GetDeletedCredits is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *MockCreditRepository_Expecter) GetDeletedCredits(ctx interface{}, userID interface{}) *MockCreditRepository_GetDeletedCredits_Call {
	return &MockCreditRepository_GetDeletedCredits_Call{Call: _e.mock.On("GetDeletedCredits", ctx, userID)}
}

func (_c *MockCreditRepository_GetDeletedCredits_Call) Run(run func(ctx context.Context, userID uint64)) *MockCreditRepository_GetDeletedCredits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreditRepository_GetDeletedCredits_Call) Return(credits []ledger.Credit, err error) *MockCreditRepository_GetDeletedCredits_Call {
	_c.Call.Return(credits, err)
	return _c
}

func (_c *MockCreditRepository_GetDeletedCredits_Call) RunAndReturn(run func(ctx context.Context, userID uint64) ([]ledger.Credit, error)) *MockCreditRepository_GetDeletedCredits_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserBalance provides a mock function for the type MockCreditRepository
func (_mock *MockCreditRepository) GetUserBalance(ctx context.Context, userID uint64) (decimal.Decimal, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBalance")
	}

	var r0 decimal.Decimal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (decimal.Decimal, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) decimal.Decimal); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(decimal.Decimal)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreditRepository_GetUserBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserBalance'
type MockCreditRepository_GetUserBalance_Call struct {
	*mock.Call
}

// GetUserBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *MockCreditRepository_Expecter) GetUserBalance(ctx interface{}, userID interface{}) *MockCreditRepository_GetUserBalance_Call {
	return &MockCreditRepository_GetUserBalance_Call{Call: _e.mock.On("GetUserBalance", ctx, userID)}
}

func (_c *MockCreditRepository_GetUserBalance_Call) Run(run func(ctx context.Context, userID uint64)) *MockCreditRepository_GetUserBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreditRepository_GetUserBalance_Call) Return(decimal1 decimal.Decimal, err error) *MockCreditRepository_GetUserBalance_Call {
	_c.Call.Return(decimal1, err)
	return _c
}

func (_c *MockCreditRepository_GetUserBalance_Call) RunAndReturn(run func(ctx context.Context, userID uint64) (decimal.Decimal, error)) *MockCreditRepository_GetUserBalance_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeDeletedCredits provides a mock function for the type MockCreditRepository
func (_mock *MockCreditRepository) PurgeDeletedCredits(ctx context.Context, olderThan time.Duration) (int, error) {
	ret := _mock.Called(ctx, olderThan)

	if len(ret) == 0 {
		panic("no return value specified for PurgeDeletedCredits")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration) (int, error)); ok {
		return returnFunc(ctx, olderThan)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration) int); ok {
		r0 = returnFunc(ctx, olderThan)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Duration) error); ok {
		r1 = returnFunc(ctx, olderThan)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreditRepository_PurgeDeletedCredits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeDeletedCredits'
type MockCreditRepository_PurgeDeletedCredits_Call struct {
	*mock.Call
}

// PurgeDeletedCredits is a helper method to define mock.On call
//   - ctx context.Context
//   - olderThan time.Duration
func (_e *MockCreditRepository_Expecter) PurgeDeletedCredits(ctx interface{}, olderThan interface{}) *MockCreditRepository_PurgeDeletedCredits_Call {
	return &MockCreditRepository_PurgeDeletedCredits_Call{Call: _e.mock.On("PurgeDeletedCredits", ctx, olderThan)}
}

func (_c *MockCreditRepository_PurgeDeletedCredits_Call) Run(run func(ctx context.Context, olderThan time.Duration)) *MockCreditRepository_PurgeDeletedCredits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreditRepository_PurgeDeletedCredits_Call) Return(n int, err error) *MockCreditRepository_PurgeDeletedCredits_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockCreditRepository_PurgeDeletedCredits_Call) RunAndReturn(run func(ctx context.Context, olderThan time.Duration) (int, error)) *MockCreditRepository_PurgeDeletedCredits_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreCredit provides a mock function for the type MockCreditRepository
func (_mock *MockCreditRepository) RestoreCredit(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RestoreCredit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCreditRepository_RestoreCredit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreCredit'
type MockCreditRepository_RestoreCredit_Call struct {
	*mock.Call
}

// RestoreCredit is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCreditRepository_Expecter) RestoreCredit(ctx interface{}, id interface{}) *MockCreditRepository_RestoreCredit_Call {
	return &MockCreditRepository_RestoreCredit_Call{Call: _e.mock.On("RestoreCredit", ctx, id)}
}

func (_c *MockCreditRepository_RestoreCredit_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCreditRepository_RestoreCredit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreditRepository_RestoreCredit_Call) Return(err error) *MockCreditRepository_RestoreCredit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCreditRepository_RestoreCredit_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockCreditRepository_RestoreCredit_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDeleteCredit provides a mock function for the type MockCreditRepository
func (_mock *MockCreditRepository) SoftDeleteCredit(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteCredit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCreditRepository_SoftDeleteCredit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDeleteCredit'
type MockCreditRepository_SoftDeleteCredit_Call struct {
	*mock.Call
}

// SoftDeleteCredit is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCreditRepository_Expecter) SoftDeleteCredit(ctx interface{}, id interface{}) *MockCreditRepository_SoftDeleteCredit_Call {
	return &MockCreditRepository_SoftDeleteCredit_Call{Call: _e.mock.On("SoftDeleteCredit", ctx, id)}
}

func (_c *MockCreditRepository_SoftDeleteCredit_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCreditRepository_SoftDeleteCredit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreditRepository_SoftDeleteCredit_Call) Return(err error) *MockCreditRepository_SoftDeleteCredit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCreditRepository_SoftDeleteCredit_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockCreditRepository_SoftDeleteCredit_Call {
	_c.Call.Return(run)
	return _c
}
